### ISSUE TITLE
Add passwordless login (using github)

### ISSUE THREAD

**Issue by mrinalwahal** [nhost/cli#107]

**Comment by regalstreak** [comment]
@mrinalwahal any update on this? Or is there a way to hack around and log in to cli for now using an auth token?

**Comment by mrinalwahal** [comment]
> @mrinalwahal any update on this? Or is there a way to hack around and log in to cli for now using an auth token?

We are working on allowing users who signed-up using social auth (GitHub) to save their passwords in console/dashboard. Then, you can simply login from the CLI using email and password.

This fix is being done on console side. Not CLI side.

It will be out soon. Hopefully within a week or two :)

**Comment by elitan** [comment]
This should go live within the next few hours. We have this working in staging.

**Comment by mrinalwahal** [comment]
We have already released a fix for this. Users who signed up on Nhost using social auth (GitHub, etc.) can save their passwords in their Nhost dashboards, and use them to login from the CLI.

I'm closing this issue.
