### ISSUE TITLE
Unable to change postgres port

### ISSUE THREAD

**Issue by defrex** [nhost/cli#11]
If I change the `postgres_port` in `config.yaml`, the service no longer boots. I believe it's because the port is mapped `3333:3333` (assuming 3333 is the new port), but doesn't change the internal postgres port. If I'm looking at this correctly, it should be mapping the custom port to the default port. Ie `3333:5432`.

**Comment by nunopato** [comment]
@defrex good catch! fixed it on a PR I already had for warning when a new CLI version is released to npm. In this initial phase, I presume lots of updates will be pushed on a regular basis.
