### ISSUE TITLE
Replace `express-js` with a custom HTTP server, for NodeJS functions

### ISSUE THREAD

**Issue by mrinalwahal** [nhost/cli#114]
The local functions server currently has to spawn a fresh `express-js` server to run NodeJS functions. We have to replace this extra dependency with a custom HTTP server to solve the same problem.

The new HTTP server must be able to parse the response structures returned by functions in following format:

```
res.status(200).send("Hello, World!)
```

**Comment by elitan** [comment]
Has been replaced by: https://github.com/nhost/functions
