### ISSUE TITLE
Running nhost fails to start

### ISSUE THREAD

**Issue by jmarbutt** [nhost/cli#117]
**Describe the bug**

**To Reproduce**
1. Create new directory `nhost-test`
2. cd `nhost-test
3. Run `nhost` 
4. See attached error log [nhost-d.log](https://github.com/nhost/cli/files/7443692/nhost-d.log)

**Expected behavior**
Should Run without failure

**Desktop (please complete the following information):**
 - OS: macOS 12.0.1
 - CLI Version: [arm64] [darwin] v0.5.6 (also tried on v0.5.7)

**Additional context**
I did a screen share with @mrinalwahal to try this a couple times and we reproduced it everytime.

**Comment by mrinalwahal** [comment]
Since this was resolved on your another machine (as per what you'd informed me), I'm closing this issue because we couldn't replicate it on our side.

Please feel free to re-open if you encounter the same problem again.
