### ISSUE TITLE
When using UI Templates, prompt to run npm install

### ISSUE THREAD

**Issue by jmarbutt** [nhost/cli#118]
**Is your feature request related to a problem? Please describe.**
When running the `nhost` and selecting `Y` to install a UI template, automatically run `npm install`

**Describe the solution you'd like**
This is minor but prompting or automatically running npm install for the `web` folder.

**Comment by mrinalwahal** [comment]
We had carefully taken a decision to not run any third-party commands (like NPM) on behalf of users from our CLI. Both because of security, and to avoid altering/modifying user's app's configuration unintentionally.

I'm closing this issue.
