### ISSUE TITLE
When using Web Templates, Prompt the desired Directory. 

### ISSUE THREAD

**Issue by jmarbutt** [nhost/cli#119]
**Describe the solution you'd like**
After asking "Do you want to install Web or Front-end templates", prompt where you would like the directory. This could default to `web`

**Additional context**
When comparing this flow to other CLIs out there, I think this is the common pattern.

**Comment by mrinalwahal** [comment]
We tend to avoid inducing too many prompts to make the app initialization process faster :)

If we happen to introduce a small change in `nhost/config.yaml` to specify the web/front-end directory, we'll let you know. But I'm closing this issue for now.

Also, it's better to stick to the standards and formats decided by Nhost for how the app should be arranged in the filesystem as we go forward into higher versions, to make sure your deployments don't fail out of unnecessary complexity.
