### ISSUE TITLE
Automatically setup package.json for Functions

### ISSUE THREAD

**Issue by jmarbutt** [nhost/cli#120]
**Describe the solution you'd like**
Automatically setup `package.json` when saying `Y` to `Do you want to install Web or Front-end templates:` and selecting `Node`. This would make it a little more obvious on the initial setup.

**Comment by mrinalwahal** [comment]
Users may not always want to run `npm init` to setup `package.json`. For example, during CI/CD or deployment pipelines.

We were trying to avoid launching commands on user's behalf as much as possible.
