### ISSUE TITLE
After upgrade, my data is wiped out

### ISSUE THREAD

**Issue by sangdth** [nhost/cli#128]
**Describe the bug**
After upgrading the cli, I can not login to my account, I went to check the database, realised all my data is gone! I don't know how to reproduce this one but pretty sure it's. I didn't change the branch.

**To Reproduce**
1. I was on version 0.5.8
2. Upgrade to 0.5.10
3. Go back to hasura database. All deleted.
4. All the metadata, columns, tables are ok, just data is gone.

**Expected behavior**
Expect data stays.

**Screenshots**
Just a blank hasura backend. Like brand new.

**Desktop (please complete the following information):**
 - OS: MacOS 12.0.1
 - Browser Chrome latest v.96.0

**Additional context**
I installed these extensions before the issue happened:
```
CREATE EXTENSION postgis;
CREATE EXTENSION postgis_topology;
```
But it works just fine. I can use the Graphiq or Postman to query etc.

**Update**
I also added new column to `users` table inside `auth`. Later I found out this causes the signup process. So I guess this one is the root cause.

**Comment by mrinalwahal** [comment]
Can you please confirm whether you are still facing this issue? If not, can you please close this issue?

**Comment by sangdth** [comment]
It does not happen again so I close it now. I will open it later if I face it again. Thanks.
