### ISSUE TITLE
`nhost -d` does not check port availability at the start

### ISSUE THREAD

**Issue by elitan** [nhost/cli#129]
**Describe the bug**
`nhost -d` does not check port availability at the start.

**To Reproduce**

1. have something running on port 1337
2. `nhost dev -d` - this will error saying the port 1337 is already in use
3. `nhost -d` - this will not error at first, instead this will start the Nhost backend locally but in the end show the following error:

```
> [proxy] [1337] listen tcp :1337: bind: address already in use
```

However, the backend is still running but won't work because it could not bind the port.

**Expected behavior**
`nhost -d` should check the port (1337 by default) and display an error and shut down if the port is not available. Just like `nhost dev -d`.

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by mrinalwahal** [comment]
Fixed and will be out in > `v0.5.11`.
