### ISSUE TITLE
Mailhog web ui port is incorrect

### ISSUE THREAD

**Issue by elitan** [nhost/cli#133]
**Describe the bug**

1. After starting `nhost dev` the CLI outputs xxx. But the URL does not work.
2. The same URL is outputted twice but it should only be outputted once.

**To Reproduce**
1. `nhost dev`
2. Click on the link in: `Emails will be sent to http://localhost:1025`

**Expected behavior**
1. Mailhog web UI should work
2. The Mailhog web URL should only be outputted once

**Screenshots**
![image](https://user-images.githubusercontent.com/331818/147072819-fadec09f-ba10-4be5-9f7c-3f67eba376ad.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version Nhost CLI v0.5.11 for darwin-arm64

**Comment by elitan** [comment]
After three restarts the CLI gave me the correct URL:

![image](https://user-images.githubusercontent.com/331818/147073681-60b6518d-852b-44f3-bad7-369c17cb48cd.png)

**Comment by mrinalwahal** [comment]
Fixed in `v0.6`.
