### ISSUE TITLE
Podman support

### ISSUE THREAD

**Issue by Herohtar** [nhost/cli#139]
**Is your feature request related to a problem? Please describe.**
I am using Podman and have `podman-docker` installed and also have configured the `DOCKER_HOST` environment variable to point to the Podman socket. By doing this I am able to run `docker-compose` without issue; however, when I try to use the Nhost CLI I get the following error message:
```text
✘ Make sure Docker is running and restart `nhost dev`
```

**Describe the solution you'd like**
I would like to be able to use Nhost CLI with Podman out of the box, or at least by modifying some configuration.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by noverby** [comment]
@Herohtar you have to set DOCKER_HOST.
```bash
export DOCKER_HOST=unix:///run/user/1000/podman/podman.sock
```

**Comment by Herohtar** [comment]
@noverby I was setting `DOCKER_HOST`, but it was just `unix:/run/user/1000/podman/podman.sock` instead of `unix:///run/user/1000/podman/podman.sock`. `docker-compose` works with the former, so I guess it's just more forgiving with the path.

In any case, fixing that issue did get me further, but `nhost dev` is still failing:
```
✘ Failed to pull image: nhost/postgres:12-v0.0.6 (16%)
ℹ Pull it manually with `docker image pull nhost/postgres:12-v0.0.6 && nhost dev` (16%)
✘ Failed to pull image: minio/minio:RELEASE.2021-09-24T00-24-24Z (33%)
ℹ Pull it manually with `docker image pull minio/minio:RELEASE.2021-09-24T00-24-24Z && nhost dev` (33%)
✘ Failed to pull image: nhost/hasura-storage:sha-623f285 (50%)
ℹ Pull it manually with `docker image pull nhost/hasura-storage:sha-623f285 && nhost dev` (50%)
✘ Failed to pull image: hasura/graphql-engine:v2.1.0 (66%)
ℹ Pull it manually with `docker image pull hasura/graphql-engine:v2.1.0 && nhost dev` (66%)
✘ Failed to pull image: nhost/hasura-auth:sha-994af31 (83%)
ℹ Pull it manually with `docker image pull nhost/hasura-auth:sha-994af31 && nhost dev` (83%)
✘ Failed to pull image: mailhog/mailhog:v1.0.1 (100%)
ℹ Pull it manually with `docker image pull mailhog/mailhog:v1.0.1 && nhost dev` (100%)

✘ Failed to initialize your environment (100%)
✔ See you later, grasshopper!
```
I believe the problem is that with Podman you have to specify the registry when pulling (it doesn't default to `docker.io` like Docker does)

For example, even with `podman-docker` installed, you can't just run `docker image pull hasura/graphql-engine:v2.1.0` because it will prompt you to select one of several registries:
```
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
? Please select an image: 
  ▸ registry.fedoraproject.org/hasura/graphql-engine:v2.1.0
    registry.access.redhat.com/hasura/graphql-engine:v2.1.0
    docker.io/hasura/graphql-engine:v2.1.0
    quay.io/hasura/graphql-engine:v2.1.0
```

You need to run `docker image pull docker.io/hasura/graphql-engine:v2.1.0` instead.

**Comment by dnk8n** [comment]
Note, since 3 months ago I think [this change](https://github.com/nhost/cli/commit/4b949ec762530886571c5beb8c1da9af5b97a904) would further make nhost incompatible with podman.

I made a feature request on podman repo, related to this here - https://github.com/containers/podman/issues/16721

**Comment by noverby** [comment]
Please keep it open :)

**Comment by dbarrosop** [comment]
CLI 1.x should work with podman, otherwise, please, feel free to open a new issue describing the problem.
