### ISSUE TITLE
config.yaml's MFA settings are not named the same way in hasura-auth

### ISSUE THREAD

**Issue by shyndman** [nhost/cli#140]
The config.yaml generated by the CLI puts MFA settings under `auth.user.mfa`, resulting in `AUTH_USER_MFA_ENABLED` and `AUTH_USER_MFA_ISSUER` env variables set in the auth container.

https://github.com/nhost/cli/blob/2b01ba4c326c766b939b971ac20accc24f86e60c/nhost/nhost.go#L1144-L1152

However, the code running in the auth container (`hasura-auth`) is looking for variables named `AUTH_MFA_ENABLED` and `AUTH_MFA_TOTP_ISSUER`. Note the discrepancies.

https://github.com/nhost/hasura-auth/blob/a5959413322415a23012d67773ca65387235503d/src/utils/env.ts#L160-L165

So who is right? The generated CLI config, or `hasura-auth`?

@mrinalwahal @elitan

**Comment by shyndman** [comment]
The `auth.token` section looks like it might be inconsistent between projects as well. There could be others.

| nhost/cli                       | nhost/hasura-auth                |
| ------------------------------- | -------------------------------- |
| `AUTH_TOKEN_ACCESS_EXPIRES_IN`  | `AUTH_ACCESS_TOKEN_EXPIRES_IN`   |
| `AUTH_TOKEN_REFRESH_EXPIRES_IN` | `AUTH_REFRESH_TOKEN_EXPIRES_IN`  |

**Comment by mrinalwahal** [comment]
The `config.yaml` file is used for local development.

The environment variables are generated recursively. So, if you want to fix this manually on your end for now, just arrange the variable `AUTH_MFA_ENABLED` in the following manner:

```
auth:
    mfa:
        enabled: true
```

Similarly you can re-arrange the variables to fix this on your end.

Apart from that, we will start looking at this bug internally. Thanks for pointing it out!

**Comment by shyndman** [comment]
Thanks!
