### ISSUE TITLE
Variables defined in .env.development not set in nhost_auth and nhost_storage containers

### ISSUE THREAD

**Issue by shyndman** [nhost/cli#141]
I wrote an `.env.development` that looks like this:

```
MY_SPECIAL_ENV_VAR=so contentful
```

Then I ran `nhost dev`, and dumped the `nhost_auth` and `nhost_storage` containers' environments — `MY_SPECIAL_ENV_VAR` was not defined in either container. 

But it should be, right?

(Oddly `MY_SPECIAL_ENV_VAR` _was_ defined in the `nhost_hasura` container's environment 🤷 )

**Comment by elitan** [comment]
Environment variables will be available in:

- Hasura
- Serverless functions

So I'd say it looks good.

**Comment by shyndman** [comment]
Ah, I see. 

Unless I'm misunderstanding, I believe this documentation will need updating. 

https://github.com/nhost/cli/#environment-variables
https://github.com/nhost/cli/wiki/Environment#envdevelopment-file

In both places, it suggests that the env variables will be available in all containers.

**Comment by mrinalwahal** [comment]
Thanks for pointing out the bug in wiki. We will update it. I'm closing this issue now.
