### ISSUE TITLE
nhost dev server panicking when requesting /v1/functions/

### ISSUE THREAD

**Issue by shyndman** [nhost/cli#142]
**Describe the bug**
I'm running the dev server locally, and just to kick the tires, visited `http://localhost:1337/v1/functions/` in my browser.

The following panic was observed:

```
> [proxy] [GET] /v1/functions/
2022/01/26 19:17:14 http: panic serving [::1]:61587: runtime error: invalid memory address or nil pointer dereference
goroutine 193 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1802 +0xb9
panic({0x1a2ccc0, 0x230cee0})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/nhost/cli/functions.(*Server).FunctionHandler.func1({0xc000036280, 0x4e}, {0x0, 0x0}, {0x800, 0xc000571590})
	/github/workspace/functions/server.go:141 +0x8d
path/filepath.Walk({0xc000036280, 0x4e}, 0xc0002537b8)
	/usr/local/go/src/path/filepath/path.go:503 +0x50
github.com/nhost/cli/functions.(*Server).FunctionHandler(0xc000277a60, {0x1ce4950, 0xc0006140e0}, 0xc000218600)
	/github/workspace/functions/server.go:176 +0xfc
net/http.HandlerFunc.ServeHTTP(0x0, {0x1ce4950, 0xc0006140e0}, 0x0)
	/usr/local/go/src/net/http/server.go:2047 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0, {0x1ce4950, 0xc0006140e0}, 0xc000218600)
	/usr/local/go/src/net/http/server.go:2425 +0x149
net/http.serverHandler.ServeHTTP({0xc0003aae70}, {0x1ce4950, 0xc0006140e0}, 0xc000218600)
	/usr/local/go/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc000208000, {0x1ceb970, 0xc0003abec0})
	/usr/local/go/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3034 +0x4e8
2022/01/26 19:17:14 http: proxy error: EOF
```

NOTE: This project does not have any functions defined.

**Comment by shyndman** [comment]
This is a result of not having a `functions/` directory.

Might be worth consider scaffolding one up front, the same way you do with the other [`LOCATIONS`](https://github.com/nhost/cli/blob/2b01ba4c326c766b939b971ac20accc24f86e60c/nhost/nhost.go#L48-L56)

**Comment by mrinalwahal** [comment]
Yes, this panic only occurs when you don't have any `functions/` dir, but you try calling functions. We are currently fixing this.

**Comment by HananoshikaYomaru** [comment]
so what is the solution? where the `functions/` dir should be put? Shouldn't an empty functions directory should be created by default?

**Comment by HananoshikaYomaru** [comment]
![CleanShot 2022-06-05 at 20 01 26](https://user-images.githubusercontent.com/43137033/172049467-39b548ac-b5a3-4bc7-91df-09369619736b.png)

The project structure is this and the nhost doc need to be updated to tell users that the `functions/` should be in the root. Or the creation of `functions/` should be made default.

**Comment by elitan** [comment]
This should be fixed in the new release: https://github.com/nhost/cli/releases/tag/v0.7.1

Let me know if you still encounter this issue after upgrading.
