### ISSUE TITLE
[serverless] Feature request: Support a wider variety of request body content-types 

### ISSUE THREAD

**Issue by shyndman** [nhost/cli#143]
I was attempting to call a serverless NodeJS function with a `text/plain` content type, and found that the body was failing to make its way to my function. `req.body` was returning `{}`.

Turns out that the function's express server has its middleware configured to limit request bodies to _only_ JSON or form encoding:

https://github.com/nhost/cli/blob/2b01ba4c326c766b939b971ac20accc24f86e60c/functions/functions.go#L59-L64

Would you consider adding additional body parsing middleware? I was thinking one for `text/*` (simple cases, where no structure is required), and one for raw bytes (protobufs, maybe small binary files, etc).

**Comment by shyndman** [comment]
Also, I'd be happy to send a PR if need be.

**Comment by mrinalwahal** [comment]
Thanks @shyndman! Please feel free to send a PR, if you can. We will review it.
