### ISSUE TITLE
Feature Request: Add support for live log tailing (like tail -f)

### ISSUE THREAD

**Issue by shyndman** [nhost/cli#145]
Sometimes it can be really nice to watch a log file and see new messages as they're coming in.

The alternative right now is to repeatedly run `nhost logs ...`, get a full dump, and find your place again — time consuming.

Live log tailing is a solid quality of life feature, and a DX win.

**Comment by elitan** [comment]
It's now possible with the new version (https://github.com/nhost/cli/releases/tag/v0.7.1).

Examples:

```
nhost logs -f postgres
nhost logs -f hasura
nhost logs -f auth
nhost logs -f storage
nhost logs -f functions
```
