### ISSUE TITLE
Error: Failed to export metadata, when initialising new app from cli

### ISSUE THREAD

**Issue by appsdevpk** [nhost/cli#147]
**Describe the bug**
just completed the installation of git, docker, nodejs and nhost cli on a windows 10 machine. when i tried to init a new app i got the below output

Name of your new app: test app
Name of your new app: test app
Do you want to install frontend templates: y
Do you want to install frontend templates: y
Selected: React-Apollo
Do you want to install functions templates: y
Do you want to install functions templates: y
Selected: Node
←[33m←[0m Downloading hasura binary for windows-386
←[31m←[0m Failed to export metadata
←[31m←[0m Failed to initialize your environment
←[32m←[0m See you later, grasshopper!p←[2Knment←[2K

**To Reproduce**
try to initialise an app on a fresh installation.

**Expected behavior**
a successful creation of nhost app

**Screenshots**
![image](https://user-images.githubusercontent.com/516860/151628357-40b491e7-3f8e-4616-80ba-00d0760a0307.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version v0.6.1

**Comment by mrinalwahal** [comment]
Please run the command again with `--debug` flag: `nhost --debug`.

The log trace will give you better information about where the CLI is failing. Show the exact error, and also preferably the log trace, and maybe we can help you better.

**Comment by appsdevpk** [comment]
here it is

Initializing environment
> [nhost] [prefix] Fetching containers
> Wrapping containers into environment
> Parsing app configuration
> [nhost_hasura] [configuration] Initializing
> [nhost_auth] [configuration] Initializing
> [nhost_storage] [configuration] Initializing
> [nhost_mailhog] [configuration] Initializing
> [nhost_postgres] [configuration] Initializing
> [nhost_minio] [configuration] Initializing
> [watcher] Activated
> Server logs will be deleted on shutdown.
> Checking for required Nhost container images
> Configuring services
> [data] Mounting data from  .nhost\main
> [nhost] [network] Preparing
> [nhost] [network] Fetching
> [nhost_auth] [container] Creating
> [nhost_auth] [container] Starting
> [nhost_storage] [container] Creating
> [nhost_storage] [container] Starting
> [nhost_mailhog] [container] Creating
> [nhost_mailhog] [container] Starting
> [nhost_hasura] [container] Creating
> [nhost_hasura] [container] Starting
> [nhost_minio] [container] Creating
> [nhost_minio] [container] Starting
> [nhost_postgres] [container] Creating
> [nhost_postgres] [container] Starting
> [nhost] [prefix] Fetching containers
> Wrapping containers into environment
> Starting health check
> [nhost_hasura] [container] Health check attempt #1 unsuccessful
> [nhost_auth] [container] Health check attempt #1 unsuccessful
> [nhost_storage] [container] Health check attempt #1 unsuccessful
> [nhost_hasura] [container] Health check attempt #2 unsuccessful
> [nhost_auth] [container] Health check attempt #2 unsuccessful
> [nhost_storage] [container] Health check attempt #2 unsuccessful
> [nhost_hasura] [container] Health check attempt #3 unsuccessful
> [nhost_auth] [container] Health check attempt #3 unsuccessful
> [nhost_storage] [container] Health check attempt #3 unsuccessful
> [nhost_auth] [container] Health check attempt #4 unsuccessful
> [nhost_storage] [container] Health check attempt #4 unsuccessful
> [nhost_hasura] [container] Health check attempt #4 unsuccessful
> [nhost_auth] [container] Health check attempt #5 unsuccessful
> [nhost_hasura] [container] Health check attempt #5 unsuccessful
> [nhost_storage] [container] Health check attempt #5 unsuccessful
> [nhost_storage] [container] Health check attempt #6 unsuccessful
> [nhost_auth] [container] Health check attempt #6 unsuccessful
> [nhost_storage] [container] Health check attempt #7 unsuccessful
> [nhost_auth] [container] Health check attempt #7 unsuccessful
> [nhost_hasura] [container] Health check attempt #6 unsuccessful
> [nhost_auth] [container] Health check attempt #8 unsuccessful
> [nhost_storage] [container] Health check attempt #8 unsuccessful
> [nhost_hasura] [container] Health check attempt #7 unsuccessful
> [nhost_storage] [container] Health check attempt #9 unsuccessful
> [nhost_auth] [container] Health check attempt #9 unsuccessful
> [nhost_hasura] [container] Health check attempt #8 unsuccessful
> [nhost_storage] [container] Health check attempt #10 unsuccessful
> [nhost_auth] [container] Health check attempt #10 unsuccessful
> [nhost_hasura] [container] Health check attempt #9 unsuccessful
> [nhost_storage] [container] Health check attempt #11 unsuccessful
> [nhost_auth] [container] Health check attempt #11 unsuccessful
> [nhost_hasura] [container] Health check attempt #10 unsuccessful
> [nhost_auth] [container] Health check attempt #12 unsuccessful
> [nhost_storage] [container] Health check attempt #12 unsuccessful
> [nhost_hasura] [container] Health check attempt #11 unsuccessful
> [nhost_storage] [container] Health check attempt #13 unsuccessful
> [nhost_auth] [container] Health check attempt #13 unsuccessful
> [nhost_auth] [container] Health check attempt #14 unsuccessful
> [nhost_storage] [container] Health check attempt #14 unsuccessful
> [nhost_storage] [container] Health check attempt #15 unsuccessful
> [nhost_auth] [container] Health check attempt #15 unsuccessful
> [nhost_hasura] [container] Health check attempt #12 unsuccessful
> [nhost_storage] [container] Health check attempt #16 unsuccessful
> [nhost_auth] [container] Health check attempt #16 unsuccessful
> [nhost_hasura] [container] Health check attempt #13 unsuccessful
> [nhost_storage] [container] Health check attempt #17 unsuccessful
> [nhost_auth] [container] Health check attempt #17 unsuccessful
> [nhost_hasura] [container] Health check attempt #14 unsuccessful
> [nhost_storage] [container] Health check attempt #18 unsuccessful
> [nhost_auth] [container] Health check attempt #18 unsuccessful
> [nhost_hasura] [container] Health check attempt #15 unsuccessful
> [nhost_storage] [container] Health check attempt #19 unsuccessful
> [nhost_auth] [container] Health check attempt #19 unsuccessful
> [nhost_hasura] [container] Health check attempt #16 unsuccessful
> [nhost_auth] [container] Health check attempt #20 unsuccessful
> [nhost_storage] [container] Health check attempt #20 unsuccessful
> [nhost_auth] [container] Health check attempt #21 unsuccessful
> [nhost_storage] [container] Health check attempt #21 unsuccessful
> [nhost_hasura] [container] Health check attempt #17 unsuccessful
> [nhost_auth] [container] Health check attempt #22 unsuccessful
> [nhost_storage] [container] Health check attempt #22 unsuccessful
> [nhost_hasura] [container] Health check attempt #18 unsuccessful
> [nhost_storage] [container] Health check attempt #23 unsuccessful
> [nhost_auth] [container] Health check attempt #23 unsuccessful
> [nhost_hasura] [container] Health check attempt #19 unsuccessful
> [nhost_hasura] [service] Health check successful
> [nhost_auth] [container] Health check attempt #24 unsuccessful
> [nhost_storage] [container] Health check attempt #24 unsuccessful
> [nhost_auth] [container] Health check attempt #25 unsuccessful
> [nhost_storage] [container] Health check attempt #25 unsuccessful
> [nhost_auth] [container] Health check attempt #26 unsuccessful
> [nhost_storage] [container] Health check attempt #26 unsuccessful
> [nhost_storage] [service] Health check successful
> [nhost_auth] [container] Health check attempt #27 unsuccessful
> [nhost_auth] [service] Health check successful
> Initializing Hasura client
>


> fork/exec C:\Users\Asus\.nhost\hasura.exe: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.


> Shutting down running services
> [nhost_mailhog] [container] Stopping
> [nhost_postgres] [container] Stopping
> [nhost_auth] [container] Stopping
> [nhost_hasura] [container] Stopping
> [nhost_storage] [container] Stopping
> [nhost_minio] [container] Stopping
> [nhost_auth] [container] Removing
> [nhost_storage] [container] Removing
> [nhost_postgres] [container] Removing
> [nhost_mailhog] [container] Removing
> [nhost_minio] [container] Removing
> [nhost_hasura] [container] Removing

**Comment by mrinalwahal** [comment]
Aah. So, the Hasura CLI for your Windows OS is not compatible.

Please do the following:

1. Download the Hasura CLI for your OS and architecture.
2. Extract and save the CLI binary as `hasura.exe` in your `$HOME\.nhost`. So, it should look like `$HOME\.nhost\hasura.exe`.
3. Restart the Nhost CLI: `nhost`

Let me know if it works.

**Comment by Ataraxy** [comment]
> Aah. So, the Hasura CLI for your Windows OS is not compatible.
> 
> Please do the following:
> 
> 1. Delete an already existing Hasura CLI binary from `$HOME\.nhost`.
> 2. Download the Hasura CLI for your OS and architecture.
> 3. Extract and save the CLI binary as `hasura.exe` in your `$HOME\.nhost`. So, it should look like `$HOME\.nhost\hasura.exe`.
> 4. Restart the Nhost CLI: `nhost`
> 
> Let me know if it works.

I had the same problem and this fixed it.

**Comment by mrinalwahal** [comment]
Since it has already worked for at least 1 person, with the proposed solution, I'm closing this issue.

If this issue persists with you, @appsdevpk, please re-open this issue.

**Comment by appsdevpk** [comment]
Thanks, it works
