### ISSUE TITLE
nhost init --remote  causes "Failed to pull migrations from remote"

### ISSUE THREAD

**Issue by acarrera94** [nhost/cli#150]
**Describe the bug**
```bash
➜ nhost init --remote        
✔ Selected: altaport-dev  Default Workspace
✘ Failed to pull migrations from remote

```

```bash
➜ nhost init --remote --debug
> Fetching user data
> Fetching saved auth credentials
✔ Selected: altaport-dev  Default Workspace
> Created /home/andre/.nhost
> Created nhost
> Created nhost/migrations
> Created nhost/metadata
> Created nhost/seeds
> Created nhost/emails
> Created .nhost/main
> Found existing nhost/config.yaml
> Found existing .env.development
> Found existing .gitignore
> Found existing .nhost/nhost.yaml
> Generating app configuration
> Saving app configuration
> Cloning github.com/nhost/hasura-auth/email-templates to nhost/emails
> Writing .gitignore
> [path] Removing .nhost/nhost.yaml
> Saving app information in .nhost/nhost.yaml
> Initializing Hasura client
> Creating migration 'init'
> Fetching metadata
> json: cannot unmarshal object into Go struct field ObjRelUsing.sources.tables.object_relationships.using.foreign_key_constraint_on of type string
```

**To Reproduce**
Created a new project,
Added tables and relations.
Nhost init --remote

**Expected behavior**
Should run successfully for a new project

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser
 - Version  Nhost CLI v0.6.1 for linux-amd64

**Additional context**
It's a new project, don't have any data in it yet.

**Comment by mrinalwahal** [comment]
As per the logs, this is clearly an issue with the schema of your Hasura instance.

Do one thing: create a new blank app locally with `nhost`. And manually replicate your Hasura schema locally.

**Comment by Herohtar** [comment]
> manually replicate your Hasura schema locally.

What does this mean and how is it done?

`nhost init --remote` is getting "Failed to pull migrations from remote" as well, but when running with debug the actual error is different:
```
...
> Initializing Hasura client
> Creating migration 'init'
> Fetching metadata
> Union does not contain array
```

**Comment by Svarto** [comment]
@Herohtar @nunopato @mrinalwahal did anyone find a solution to this? 

I have the same issue and same error message ("Union does not contain array"), I am not able to set up a local dev environment from an existing project on nhost v2. 

Manually replicating my remote Hasura schema is not an option, this is an app already in production that has significant backend setup (incl. custom SQL functions, tables, triggers, custom fields etc etc)

**Comment by mrinalwahal** [comment]
There is clearly a problem in the schema of your app. It's not getting saved locally.

I'm afraid manually migrating the app to a new local blank app might be the only immediate fix for now.

Just export your hasura metadata from production app, and import it locally.

**Comment by Svarto** [comment]
@mrinalwahal thanks for the reply. 

This doesn't work, see below for error I get. I tried to copy what migrations exist in the failed remote project, into a blank project, start it up, import metadata as you recommended. But it doesn't work
![image](https://user-images.githubusercontent.com/24279217/158989394-e8818c17-fad5-49de-a4d3-8181299f38a7.png)

**Comment by mrinalwahal** [comment]
@Svarto first just delete all the migrations. Start a purely blank app. And just load the metadata. And see if that works. Then we'll come to migrations.

**Comment by Svarto** [comment]
@mrinalwahal OK, tried this, I get the same error because the underlying datastructure in postgres does not match the metadata - so trying to import the metadata in Hasura created the same error as above.

**Comment by Eun** [comment]
Please test with nhost version v0.6.6.
If the problem still occurs I will reopen this issue.

**Comment by Herohtar** [comment]
This appears to have fixed the error for me.
