### ISSUE TITLE
CLI doesn't install express when installing a functions template.

### ISSUE THREAD

**Issue by FuzzyReason** [nhost/cli#153]
CLI doesn't install express when creating a new project with a functions template.

```
Do you want to install functions templates: y
✔  Selected: Node
✔  Your app is running at http://localhost:1337 (Ctrl+C to stop)
ℹ  Emails will be sent to http://localhost:8818
⚠ Run `npm init && npm i && npm i express` to use functions

✘ Failed to initialize functions server
✔ See you later, grasshopper!% 
```

**Comment by mrinalwahal** [comment]
I think the decision to **not** run terminal commands, like `npm i`, on behalf of the user automatically was taken consciously while I was in the team.

But maybe we can add an additional consent [Y/N] to ask the user whether to run it for them.

**Comment by elitan** [comment]
The concept of templates has been removed in the latest release.
