### ISSUE TITLE
Browser tab duplication when starting an application locally

### ISSUE THREAD

**Issue by FuzzyReason** [nhost/cli#155]
When creating a local app with CLI and starting it, it automatically opens a tab with Hasura Console on port `1337.` If killing the app in the terminal and starting it again (without closing the tab in the browser), it opens a new one. 

It would be nice to check if the user has a tab open with `http://localhost:1337`, so the tab with Hasura Console becomes active without opening a new one.

**Comment by szilarddoro** [comment]
This issue is experienced in `Chrome (Version: 98.0.4758.102)`. It's working fine if `Safari (Version: 15.3 (17612.4.9.1.5))` is the default browser.

**Comment by nunopato** [comment]
@szilarddoro I don't think this is something we can easily do with the CLI. I think this would require hooking into the browser's API and asking whether that particular window is open. Safari probably does that by default. Closing this issue now.
