### ISSUE TITLE
.env.development should be written (empty) even if no env vars being used

### ISSUE THREAD

**Issue by elitan** [nhost/cli#16]
Otherwise `nhost dev`won't work

╭─eli@johans-mbp.lan ~/tmp/facebook2
╰─➤  nhost dev
development environment is launching...first run takes longer to start
Couldn't find env file: /Users/eli/tmp/facebook2/.env.development
Error: Command failed: docker-compose -f ./.nhost/docker-compose.yaml config
Couldn't find env file: /Users/eli/tmp/facebook2/.env.development
    at DevCommand.run (~/.npm-packages/lib/node_modules/nhost/src/commands/dev.js:147:5)
    at DevCommand._run (~/.npm-packages/lib/node_modules/nhost/node_modules/@oclif/command/lib/command.js:44:31)
````

https://github.com/nhost/cli/blob/master/src/commands/init.js#L118

**Comment by nunopato** [comment]
Fixed on https://github.com/nhost/cli/pull/14
