### ISSUE TITLE
Issue while creating a new app through nhost cli

### ISSUE THREAD

**Issue by dikshatekriwal** [nhost/cli#160]
**Describe the bug**
Failing to create an app through nhost cli in windows.

**To Reproduce**
1. nhost -d 
2. Enter app name
3. Starting containers in docker
4. See error - fork/exec C:\Users\IM0265\.nhost\hasura.exe: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

**Expected behavior**
Successfully create an app, for upgrading from V1 to V2

**Screenshots**
![3](https://user-images.githubusercontent.com/15191000/156304444-6a62435d-05c8-4357-bafe-ff6d9507a55a.png)
![2](https://user-images.githubusercontent.com/15191000/156304439-ec96de42-b7cb-44e7-abad-4791e4ba8108.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Browser chrome
 - Version v0.6.2 for windows-386

**Comment by mrinalwahal** [comment]
The Hasura CLI that has been downloaded in your system isn't compatible with windows.

Try [this out](https://github.com/https://github.com/nhost/cli/issues/147#issuecomment-1025152659). This should solve your problem.

But this isn't a bug in the CLI.

**Comment by dikshatekriwal** [comment]
@mrinalwahal the above solution worked. Thanks a lot.
