### ISSUE TITLE
WSL2 Issue - Accessing functions server from Hasura

### ISSUE THREAD

**Issue by thetre97** [nhost/cli#168]
**Describe the bug**
When running `nhost dev` from inside WSL2, Hasura cannot access the functions server via the assigned `NHOST_BACKEND_URL` variable value.

**To Reproduce**
1. Make sure you using WSL2.
2. Create a simple `/functions/test.ts` function, adding a console log to show it has been called (and returning some data if using an action).
3. Run `nhost dev`
4. Create either an action or an event in Hasura via the console, and set the URL to your function (including the `NHOST_BACKEND_URL` env): `{{NHOST_BACKEND_URL}}/v1/functions/test`. You may also want to set the timeout to ~5s.
5. Run the action/event handler from within Hasura, and wait for the timeout and subsequent error message.

**Expected behavior**
Hasura should be able to access the functions server via `localhost` or the (likely more useful) `NHOST_BACKEND_URL` env, which is set to an internal IP address .

**Desktop (please complete the following information):**
 - OS: Windows 11, WSL2 (Kernel version  `5.10.60.1`, running Ubuntu `20.04`)
 - Browser: N/A
 - Version: `v0.6.4 for linux-amd64`

**Additional Context**
- Likely a similar issue to: https://stackoverflow.com/questions/65327238/cant-connect-to-wsl2-localhost-server-from-wsl2-docker-container

**Comment by elitan** [comment]
Thanks for reporting this issue.

Quick question: What's the value of `NHOST_BACKEND_URL` inside the Hasura container?

**Comment by thetre97** [comment]
The value is: `"NHOST_BACKEND_URL=http://172.24.229.11:1337"`

**Comment by elitan** [comment]
Seem to be related to:

https://github.com/microsoft/WSL/issues/4150

Workaround solution: https://github.com/microsoft/WSL/issues/4150#issuecomment-504209723

If anyone could test this (@thetre97) that would be awesome.

**Comment by thetre97** [comment]
I unfortunately can't get it to work 😕

**Comment by elitan** [comment]
This is fixed in the latest version.
