### ISSUE TITLE
Nhost purge does not purge images 

### ISSUE THREAD

**Issue by ArieJones** [nhost/cli#172]
**Describe the bug**

**To Reproduce**
1. run nhost purge 
2. check docker to ensure images are purged 

**Expected behavior**
That the docker images should be purged 

**Screenshots**
After updating yaml file to get 0.5.0 of hasura-auth and then running nhost purge 

![image](https://user-images.githubusercontent.com/14859781/161103226-14984a94-56ae-4ea1-8c74-67814a87a1de.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 - WSL2 
 - Version v0.6.5 for linux-amd64

**Comment by mrinalwahal** [comment]
It wasn't supposed to purge the images anyway. Only delete the containers in case they are running. You will have to manually delete the images.
