### ISSUE TITLE
User access to file storage forbidden after upgrade

### ISSUE THREAD

**Issue by jovermier** [nhost/cli#203]
**Describe the bug**
After upgrading from v0.6.5 to v0.6.6 and running the nhost platform locally, logged in users are no longer able to access files they were able to previously.

**To Reproduce**
1. Install nhost cli v0.6.5
2. Set user insert and select permissions.
3. With logged in user, upload files.
4. With logged in user, access files and notice the user can download the files.
5. Upgrade to nhost cli v0.6.6
6. With logged in user, access files and notice the user cannot download the files. Error code 403 access denied.

**Expected behavior**
User should be able to access the files they are configured to access.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version v0.6.6

**Additional context**

**Comment by jovermier** [comment]
I configured buckets and files to be public. The api now returns a 500 when trying to fetch the file. Looking into the nhost_storage container, The log show `NoSuchKey: The specified key does not exist.\n\tstatus code: 404`. I then added a new file and noticed a file structure change. The upgrade script probably should have moved these files. The new file is highlighted in the screenshot.
![image](https://user-images.githubusercontent.com/7989760/164752549-0b5cb600-74d7-46e0-8ef5-04dc531edecf.png)

**Comment by dbarrosop** [comment]
> I configured buckets and files to be public

yes, this was a bug that was fixed already and will be released on monday

> then added a new file and noticed a file structure change. The upgrade script probably should have moved these files.

I think this is a problem with a cli change that was done, I will look into it and fix it but there shouldn't have been any change to the structure.

**Comment by dbarrosop** [comment]
Would you mind testing #203? If you tell me which OS/architecture you are using I can build a binary for you.

**Comment by jovermier** [comment]
I built the main branch binary, verified it worked the same. I then built your 203 branch and tested. The 203 version was not able to access the files in neither `data/nhost` nor `data/nhost/nhost`. It was also not able to upload new files.

**Comment by dbarrosop** [comment]
Apologies, I made a mistake in the fix and I was so convinced it was the right thing that I didn't event test it myself. Anyway, I corrected the mistake and tested it this time, it should work now. It'd be great if you could confirm though before mergint. Thanks!

**Comment by jovermier** [comment]
Your latest changed fixed the issue. I had to manually move some files new uploads around in both `data/nhost` and `data/.mino.sys` to the originally intended file location.
