### ISSUE TITLE
Golang nhost client sdk for Web, Mobile and Desktop apps built with golang.

### ISSUE THREAD

**Issue by gedw99** [nhost/cli#214]
I use GIOUI, which is a golang framework for building, web, desktop and mobile apps. 
Heres some links about it:
https://gioui.org/
https://github.com/orgs/gioui/repositories

[github.com/hasura/go-graphql-client](https://github.com/hasura/go-graphql-client) will compile within GIOUI. 
I have not checking yet if it works for the WASM compile target ( https://gioui.org/doc/install/wasm)

**Comment by dbarrosop** [comment]
Hello, I am not sure if you have a question but if you are looking for a golang client we don't have an official one even though `hasura-storage` comes with one (only for the storage though):

https://pkg.go.dev/github.com/nhost/hasura-storage/client

**Comment by gedw99** [comment]
I am using the https://pkg.go.dev/github.com/nhost/hasura-storage/client currently to play around with GIOUI talking to the server. 

What API do the JS GUI's hit on the server please ? Is it graphql ?  Can you link me to the code ? I am hopeless at JS these days :)
