### ISSUE TITLE
nhost init --remote does not include custom SQL functions in the migration.sql file

### ISSUE THREAD

**Issue by ctrlemo** [nhost/cli#218]
**Describe the bug**
I ran the following command
nhost init --remote

As expected it created a new Nhost project folder containing the latest Production hasura metadata and postgres migration schema.
However the postgres schema, was missing all my custom postgres database functions.

**To Reproduce**
1. Create a Nhost production project
2. Run your local version of Nhost and create new tables and a couple of database functions. You can use this example https://hasura.io/docs/latest/graphql/core/databases/postgres/schema/custom-functions/
3. Commit it to your git repo, and push in order to deploy to production.
4. run nhost init --remote on your local in order to grab the latest production metadata and postgres schema.
5. the postgres schema migration file contain tables, views, but none of the Custom SQL functions are that were created.

**Expected behavior**
All postgres schema types including sql functions that are custom made by user should be pulled down into the migration file.
Because if for any reason you want to start from scratch based on a production instance of nhost, you would like your postgres schema migration file to be complete with all your schema types.

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]
 - Version v0.6.7

**Additional context**
The same can be reproduced, without deploying through Git, but just making database tables and use defined functions directly on production. And afterwards running "nhost init --remote"

**Comment by oristian** [comment]
I had the same experience today, on the latest `nhost cli @0.6.10`

**Comment by ctrlemo** [comment]
👍🏽
