### ISSUE TITLE
Sign in with GitHub

### ISSUE THREAD

**Issue by plmercereau** [nhost/cli#220]
`nhost login` asks the user for their email/password.
Some users use exclusively GitHub to authenticate to the cloud, we may want to reflect that into the CLI

**Comment by szilarddoro** [comment]
Sign in with your GitHub user on https://app.nhost.io and create a password for your account (Click on avatar in the top right corner => Change password). You can use this password to sign in to the CLI.

**Comment by plmercereau** [comment]
sure it's not blocking, but some users can consider oauth is enough

**Comment by dylan-hoefsloot** [comment]
Can we add this to the documentation? It was not obvious and I had to come search the issues to find the solution, ideally you would be able to login with the oauth you signed up with.

**Comment by dbarrosop** [comment]
This is already supported.
