### ISSUE TITLE
containers are not stopped on quit if nhost were running for days

### ISSUE THREAD

**Issue by kratam** [nhost/cli#222]
**Describe the bug**
When the local nhost runs for a long time, it fails to stop the docker containers after hitting ctrl+c

**To Reproduce**
Don't know how to reproduce but it happens almost every time for me.

**Expected behavior**
nhost quits and the containers are stopped.

**Screenshots**
```
^C> [path] Removing ../../../../../../../../var/folders/zw/qm_ff5mn0979b6ckj3k6zs1c0000gn/T/304297052
> [proxy] [1337] http: Server closed
> [console] os: process already finished
> [functions] [7777] http: Server closed
> [path] Removing ../../../../../../../../var/folders/zw/qm_ff5mn0979b6ckj3k6zs1c0000gn/T/1969365865
```

**Desktop (please complete the following information):**
 - OS: macOS 12.3
 - Version v0.6.7

**Comment by elitan** [comment]
This is fixed in the latest release.
