### ISSUE TITLE
nhost init --remote does not pull down the auth features that are enabled in the cloud

### ISSUE THREAD

**Issue by GavanWilhite** [nhost/cli#227]
When using nhost init --remote the resulting config does not have the auth features enabled that were enabled in the cloud (specifically tested with passwordless). This leads to getting a DisabledEndpointError when trying to use auth strategies that work in the cloud.

**Comment by Alex-Ferreli** [comment]
Same issue happen with latest version (v0.8.6).

**Comment by elitan** [comment]
`nhost init --remote` only pulls the following for now:

- Database migrations
- Hasura Metadata

We're working on a new model for configuration that `nhost init --remote` should support.
