### ISSUE TITLE
Postgres Permission issues  at /var/lib/postgresql/data

### ISSUE THREAD

**Issue by joshua1** [nhost/cli#235]
I am experiencing permission issues when running nhost via cli (nhost dev), even after running with sudo.
``` 
chmod: changing permissions of '/var/lib/postgresql/data': Operation not permitted
```
Is there a way to specify a different directory with the permission issues on /var/lib/postgresql/data . Running Hasura_auth from the project however does not give this error. Hasura_auth works ok and the docker-compose file is accessible ( I didn't have to make any change even).

Only Issue i have seen so far is the 
```
chmod 777
```
 call in the CLI . on my system , company policy is not allowing that command on /var/lib/* that the CLI is trying to do . Is it possible to change this location via config.yaml to a location within the control of the current user ? or do away with that command entirely , cos i don't have any issues starting Hasura-auth and Hasura CLI Porjects where this is not a thing .

**Comment by dbarrosop** [comment]
Those commands are not run in your system, they are run in a docker container. Would you mind describing which operating system and container engine/application are you running? We have seen that issue with people using podman, colima and other alternative solutions to the docker.

https://github.com/nhost/cli/issues/148

**Comment by dbarrosop** [comment]
> just wondering if this (chmod 777) can be changed to the current user instead of everyone

@shiftlabs1 if the issue is what i think it is (see my previous comment), the user doesn't matter, it is a problem with either the virtualization layer (if using macos/windows) and/or the containerization layer

**Comment by elephant3** [comment]
@joshua1 could you confirm that's still an issue in the latest CLI version?
