### ISSUE TITLE
Run any Hasura CLI command

### ISSUE THREAD

**Issue by jovermier** [nhost/cli#254]
Hasura cli provides a squash feature to squash migration files down into a single file. Allow Hasura cli to work with nhost directory or add similar functionality to Nhost cli.

[https://hasura.io/docs/latest/graphql/core/hasura-cli/hasura_migrate_squash/](https://hasura.io/docs/latest/graphql/core/hasura-cli/hasura_migrate_squash/)

**Comment by plmercereau** [comment]
In broader terms, I would suggest the CLI should be able to run any hasura console command

**Comment by elitan** [comment]
I've updated the title of this post to reflect a more general suggestion.

Something like this could work:

```
nhost hasura <any hasura command>
```

To support all commands [here](https://hasura.io/docs/latest/hasura-cli/commands/index/). The commands would be run with the correct `--endpoint` and `--admin-secret` flags for the current project.

**Comment by Rigel772** [comment]
When I try:
```
nhost hasura migrate create init --from-server --endpoint https://domain.name.com --admin-secret o4QzbZ
```
I am getting
`Error: unknown command "hasura" for "nhost"`

I am trying to migrate existing self hosted Hasura project to self  hosted Nhost instance.
I have all data in "public" schema, I am hoping the migration would not affect the Nhost's "auth" and "storage", right?
