### ISSUE TITLE
Hasura upgrade

### ISSUE THREAD

**Issue by hotrush** [nhost/cli#256]
I noticed that hasura version is locked to 2.2.0 when the most actual one is 2.8.3 (same in the cloud I think). Any luck to have it upgraded to the latest version? I think it is quite important to use latest software versions, also some feature are missing such as stream subscriptions.

**Comment by joserocha3** [comment]
Version can be added to `nhost/config.yaml`.

```
services:
  hasura:
    version: v2.8.3
```

There are some details in the [CLI wiki](https://github.com/nhost/cli/wiki/Configuration-Design), but it's not very descriptive.

**Comment by elitan** [comment]
We will be more responsive to Hasura version updates in the future.

If you want to set a custom Hasrua version you can do so in `nhost/config.yaml` like this:

```
services:
  hasura:
    image: hasura/graphql-engine:v2.8.3
```
