### ISSUE TITLE
More logs in `nhost dev` during check images?

### ISSUE THREAD

**Issue by dminkovsky** [nhost/cli#260]
**Is your feature request related to a problem? Please describe.**
Pulling images in `nhost dev` takes a long time depending on connection speed. Unless you know images are being pulled and know to monitor `docker images`, you don't really know what's going on.

**Describe the solution you'd like**
The CLI could log info/progress as images are pulled.

**Describe alternatives you've considered**
I haven't considered other alternatives

**Additional context**
First time nhost CLI user. Platform seems perfect. Can't wait to dig in.

**Comment by dminkovsky** [comment]
Actually the `-d` debug switch provides a good amount of information, in my opinion anyway! Not noisy, all relevant stuff.

**Comment by elitan** [comment]
Yes running `nhost up -d` (in debug mode) works well.
