### ISSUE TITLE
Make NHOST_BACKEND_URL an env var for local dev

### ISSUE THREAD

**Issue by fungilation** [nhost/cli#269]
`NHOST_BACKEND_URL`=http://localhost:1337/ even when it's removed from .env.development. This is due to it being a system var that cannot be changed.

This should be changeable for local dev. Use case: Local function is always fetching gql endpoint under NHOST_BACKEND_URL domain. Letting NHOST_BACKEND_URL be defined as an env var means easy pointing of local function in working with data on any deployed Nhost app.

`NHOST_BACKEND_URL` if not defined, should still default to http://localhost:1337/

**Comment by kratam** [comment]
Another use-case: I have a hasura cron which calls an nhost function => this function calls an external queue and passes `NHOST_BACKEND_URL` as the url => the queue should call another nhost function at this url (but cannot reach `http://traefik:1337` which is a hard-coded URL in the new CLI)
