### ISSUE TITLE
Nhost up requires the Internet

### ISSUE THREAD

**Issue by dminkovsky** [nhost/cli#273]
**Is your feature request related to a problem? Please describe.**

My power went out. I'd like to work on my app. However, when I do nhost up, it crashes while pulling docker images, even though I already have them.

**Describe the solution you'd like**

The cli shouldn't fail if I already have the necessary images.

**Comment by elephant3** [comment]
Fixed in the recent release. However, it still requires internet connection when you do `nhost init` because it pulls email-templates from github. If you have your project set up and all docker images are downloaded, then you won't have the issue anymore.

**Comment by dminkovsky** [comment]
Yes! Tested yesterday on my flight :) Thank you very much.
