### ISSUE TITLE
nhost init --remote throws error on a new project

### ISSUE THREAD

**Issue by dohomi** [nhost/cli#274]
**Describe the bug**
I installed the CLI and run `nhost init --remote` on a new created project and not able to proceed.

**To Reproduce**

1. nhost init --remote
2. check the error message

```
⚙ Creating your app...panic: interface conversion: interface {} is nil, not []interface {}

goroutine 1 [running]:
github.com/nhost/cli/hasura.(*Client).GetSchemas(0x14000831678, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/runner/work/cli/cli/hasura/hasura.go:159 +0x6fc
github.com/nhost/cli/cmd.pullMigration(0x140005cea80, 0x26, 0x14000114120, 0x20, 0x14000252c60, 0x140005ceab0, 0x21, 0x140000b4460, 0x7, 0x7, ...)
        /home/runner/work/cli/cli/cmd/pull.go:146 +0x17c
github.com/nhost/cli/cmd.glob..func12(0x105f1eb20, 0x140002bec70, 0x0, 0x1)
        /home/runner/work/cli/cli/cmd/init.go:250 +0xa14
github.com/spf13/cobra.(*Command).execute(0x105f1eb20, 0x140002bec60, 0x1, 0x1, 0x105f1eb20, 0x140002bec60)
        /home/runner/work/cli/cli/vendor/github.com/spf13/cobra/command.go:860 +0x1d0
github.com/spf13/cobra.(*Command).ExecuteC(0x105f1f520, 0x104cdc454, 0x1400018e058, 0x1400018e000)
        /home/runner/work/cli/cli/vendor/github.com/spf13/cobra/command.go:974 +0x264
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/work/cli/cli/vendor/github.com/spf13/cobra/command.go:902
github.com/nhost/cli/cmd.Execute()
        /home/runner/work/cli/cli/cmd/root.go:120 +0x30
main.main()
        /home/runner/work/cli/cli/main.go:31 +0x20

```
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. v0.5.0. Command to get your version: `nhost version`]

**Additional context**

**Comment by elitan** [comment]
This should be fixed in the latest release. Can you try to update to the latest version?

Let me know here if you still encounter problems.

**Comment by GSManganneau** [comment]
Hello everyone,

I recently installed nhost CLI  and I have the same issue

Anyone for helping ?

**Comment by elephant3** [comment]
> Hello everyone,
> 
> I recently installed nhost CLI and I have the same issue
> 
> Anyone for helping ?

Did you link a github repo to your project or not?

**Comment by phlogios** [comment]
I have the same issue today, with github repo linked.
As reported in https://github.com/nhost/cli/issues/627 (sorry didn't see this issue was already reported)
