### ISSUE TITLE
I don't see windows versions in the 0.7.x releases

### ISSUE THREAD

**Issue by yureckey** [nhost/cli#288]
this

**Comment by elitan** [comment]
We only support WSL2 from 0.7.x. We haven't tried it on native Windows.

**Comment by yureckey** [comment]
Soooo, does this mean I can't use CLI on Windows?
That's not cool, given that ONLY way (afaik) to modify email templates are using CLI to sync local and remote app and upload templates (and same cumbersome procedure for Functions)

**Comment by vipafattal** [comment]
So does that mean you are not continuing support for Windows CLI or in future releases will be available for windows?
