### ISSUE TITLE
nhost init fails when trying to access userData.user.teams

### ISSUE THREAD

**Issue by alexraison** [nhost/cli#29]
Running the command: 
`nhost init -e https://hasura-<nhost_endpoint>.nhost.app -a <admin_password>` 

fails with the error:
`TypeError: userData.user.teams.flatMap(...) is not a function or its return value is not iterable`

Does this command work without my user being part of a team?

**Comment by nunopato** [comment]
@alexraison sorry for the late reply, Alex. Which version are you using? We pushed a few fixes in the meantime that might have fixed your issue. Please try again and let me know the result. 

Also, on the latest version, `init` does not accept any arguments. Running `nhost init` will start an interactive prompt and ask you to pick one project.

Feel free to reach out to me directly on discord!

**Comment by alexraison** [comment]
Hi @nunopato, I'm using nhost/0.0.18 darwin-x64 node-v10.17.0 which still has the same issue.

**Comment by nunopato** [comment]
closing this issue now, @alexraison and I synced via discord.

**Comment by akd-io** [comment]
For future developers running into this issue, I was able to solve it by upgrading to Node 14.
