### ISSUE TITLE
nhost init fails when trying to export seed data

### ISSUE THREAD

**Issue by alexraison** [nhost/cli#30]
Running the command:
`nhost init -e https://hasura-<nhost_endpoint>.nhost.app -a <admin_password>`

fails with the error:
`Error! Command failed: hasura seeds create roles_and_providers --from-table auth.roles --from-table auth.providers --endpoint https://hasura-<nhost_endpoint>.nhost.app --admin-secret <admin_password> --skip-update-check
time="2020-10-19T13:57:18+13:00" level=fatal msg="exporting seed data: [unexpected] error while executing pg_dump: pg_dump: error: no matching tables were found\n ($)"`

When I try to run the Hasura CLI command directly e.g.
`hasura seeds create roles_and_providers --from-table auth.roles --from-table auth.providers --endpoint https://hasura-<nhost_endpoint>.nhost.app --admin-secret <admin_password> --skip-update-check`
I get the same error message but this is a brand new nhost project.

I'm running the CLI on OS X Catalina 10.15.6 if that's relevant.

**Comment by elitan** [comment]
@alexraison What `hasura` version do you run?

`hasura version`

**Comment by elitan** [comment]
The reason is Hasura's CLI had a bug in their latest version. @nunopato added a fix for it here: https://github.com/hasura/graphql-engine/pull/5710

I'm running `hasura v1.3.0` and it works.

I'm installing `hasura` like so: `npm i -g hasura-cli@1.3.0`

**Comment by nunopato** [comment]
@alexraison hasura v1.3.3 is out with the fix @elitan mentioned... closing this issue now

**Comment by elitan** [comment]
For me it failed again. I had to remmove the `.hasura` folder in my home directory:

```
$ rm -rf ~./hasura
```

Then `nhost init` worker again.
