### ISSUE TITLE
Knowing when CLI has completed all startup steps and all containers are healthy

### ISSUE THREAD

**Issue by elitan** [nhost/cli#303]
Currently, there is no way of knowing when the CLI has completed all startup steps (applying migrations, metadata import/export, seeds, the restart of containers, etc.), and all containers are up and healthy.

This causes problems in CI environments where we need to start `nhost up` and run tests **after** all startup steps and all containers are healthy.

For example, we're relying on `/v1/auth/healthz` here (https://github.com/nhost/nhost/blob/fix/storage-in-node/packages/hasura-storage-js/package.json#L47). The problem is that this `/v1/auth/healthz` endpoint can respond with `200` for a few seconds **before** all startup steps are completed.

**Comment by dbarrosop** [comment]
I am guessing this is for scripting/CI purposes. In that case I'd suggest instead adding a `--background` flag (i.e. `nhost up --background`) that instead does everything that it needs doing and everything has been checked and then  exits the program without stopping any container and setting a proper status code (0 for success, non-0 for errors). That way `nhost up -d` could be easily used in any shell script or CI seamlessly.

**Comment by elitan** [comment]
We solved this in our CI by making a GET (not HEAD) request to the Hasura console at `http://localhost:9695`, which is the last service that starts after all containers are healthy.
