### ISSUE TITLE
Cli ask's me to login over and over again

### ISSUE THREAD

**Issue by Anan7Codes** [nhost/cli#307]
I created an account on nhost and I sign in with my github. However when I try to sign in onto nhost cli, I enter my github email and password and it says successfully authenticated but any command I run after that, it asks me to enter my credentials again which also fails.

<img width="577" alt="Screen Shot 2022-08-24 at 8 47 43 PM" src="https://user-images.githubusercontent.com/37017231/186476737-a989078f-ca9f-47e0-bee4-d955f325860f.png">

**Comment by linden** [comment]
running `rm -rf ~/.nhost` fixed this for me (macOS).

**Comment by Anan7Codes** [comment]
> running `rm -rf ~/.nhost` fixed this for me (macOS).

I'm still facing the same issue :(

**Comment by linden** [comment]
> > running `rm -rf ~/.nhost` fixed this for me (macOS).
> 
> 
> 
> I'm still facing the same issue :(

I also reset my password, have you tried that?

**Comment by elephant3** [comment]
@Anan7Codes What version of CLI do you use?

**Comment by Anan7Codes** [comment]
> @Anan7Codes What version of CLI do you use?

Nhost CLI v0.7.9 for darwin-arm64

**Comment by Anan7Codes** [comment]
> > > running `rm -rf ~/.nhost` fixed this for me (macOS).
> > 
> > 
> > I'm still facing the same issue :(
> 
> I also reset my password, have you tried that?

Since I'm using github auth, should I reset my github password?

**Comment by elitan** [comment]
If you're using GitHub to sign in to Nhost please set a Nhost password for your account:

![CleanShot 2022-09-02 at 10 51 47](https://user-images.githubusercontent.com/331818/188102573-fffb9237-0c23-44a7-aabc-e0c6733f26f2.png)

However, we should improve the error message from the CLI to clearly state what's happening (success/failure) when signing in.

**Comment by Anan7Codes** [comment]
> If you're using GitHub to sign in to Nhost please set a Nhost password for your account:
> 
> ![CleanShot 2022-09-02 at 10 51 47](https://user-images.githubusercontent.com/331818/188102573-fffb9237-0c23-44a7-aabc-e0c6733f26f2.png)
> 
> However, we should improve the error message from the CLI to clearly state what's happening (success/failure) when signing in.

Thanks Johan this worked :))

**Comment by elitan** [comment]
Perfect. Let's leave this issue open to fix the CLI with better messaging around what's happening during sign-in.
