### ISSUE TITLE
NHOST_BACKEND_URL not functioning as expected 

### ISSUE THREAD

**Issue by ArieJones** [nhost/cli#308]
It appears as if some recent changes in the cli have created a problem. We used to be able to use the nhost-js  client and use the NHOST_BACKEND_URL environment variables to wire up a client in order to make calls to the graphql instance. However, with the current set of changes the NHOST_BACKEND_URL is set to the http://traefik:1337 which doesn't work and you will get a connection error. 

If you try to override the NHOST_BACKEND_URL in your local environment file.... then things like the Hasura actions start to break if you are using it. 

If you try to put in a different environment variable to use the old http://localhost:1337 ... this does not work because it can't route to that from the functions docker instance.

I would propose that a simple fix would be to add the environment variable 
HASURA_ENDPOINT similar to what is provided with storage 

Thanks!

**Comment by elitan** [comment]
Could you describe your use case in detail, so I understand your specific problem?

**Comment by elitan** [comment]
Related issue: https://github.com/nhost/cli/issues/269

**Comment by elitan** [comment]
@elephant3 Is there something we can do here to change `traefik` to `localhost` so it works with Docker, Docker networks, and Traefik?

**Comment by ArieJones** [comment]
So we have the ability to process stored tokens for monthly payment plans that we don't want the keys exposed to the front end .... 

so we put that logic away on the back end .... 

but as part of that process we have to call a bunch of graphql queries to find out other information .. such as the token for the account .. how much .. yadda yadda... 

and to update values after it is processed... was it paid? did we receive an error? 

Previously we were able to use NHOST_BACKEND_URL ... use the js library to construct an NhostGraphqlClient for us ... and then make or call out to Hasura... 

but since this somewhat recent change... our local dev.. and heck maybe production for all I know .... is broken

**Comment by ArieJones** [comment]
> Where exactly do you use the `NHOST_BACKEND_URL` with the nhost-js client? In Next.js or something?

I am proposing that we just put an environment variable on the functions instance... which is what the PR is about up there.. 

I am assuming that we would need to add that environment variable to the production instances to.

**Comment by elitan** [comment]
From where did you do those calls with the js library using the `NHOST_BACKEND_URL`?

The values in prod are unchanged. The value of `NHOST_BACKEND_URL` was changed in the CLI because we're now running functions inside a Docker container and the same Docker network as all other containers together with Traefik. Nothing in prod has changed regarding system environment variables.

**Comment by ArieJones** [comment]
> @elephant3 Is there something we can do here to change `traefik` to `localhost` in the `NHOST_BACKEND_URL` env var so it works with Docker, Docker networks, and Traefik?

I have tried using localhost.... but I think because the functions are in their own container ... localhost doesn't mean much to them

**Comment by elitan** [comment]
> > Where exactly do you use the `NHOST_BACKEND_URL` with the nhost-js client? In Next.js or something?
> 
> I am proposing that we just put an environment variable on the functions instance... which is what the PR is about up there..
> 
> I am assuming that we would need to add that environment variable to the production instances to.

It feels hacky, and we must update system env vars for prod if we do so. 

Maybe we can solve this issue more elegantly.

**Comment by ArieJones** [comment]
> the same Docker network as all other

Ok then my prod should be unaffected right now.. because I haven't pushed up any of the updates from when I updated the CLI ... because I ran into a problem upgrading where it wiped all my data out of the database... 

But I think if you are going to be consistant .. then you'll probably have to add the environment variable to the functions container .. if for nothing else than to not have us lowly developers have to write a code to determine if we are local or not ... 

lol

**Comment by elitan** [comment]
I'm closing this as everything is working as expected with NHOST_BACKEND_URL for internal communication between functions and other Nhost services.
