### ISSUE TITLE
Storage port not forwarded causes issues with presigned URL

### ISSUE THREAD

**Issue by acarrera94** [nhost/cli#311]
**Describe the bug**
When a request is made to the presigned url after that url is generated. It fails because the url is wrong.

**To Reproduce**
Use the latest CLI
generate a presigned url with nhost-js 

The response will be something like: 
```
{"url":"http://localhost:8576/v1/files/5bdb6940-9c00-49c8-96ce-50bdcfa316e6/presignedurl/content?X-Amz-Algorithm=AWS4-HMAC-SHA256\u0026X-Amz-Credential=minioaccesskey123123%2F20220825%2Fno-region%2Fs3%2Faws4_request\u0026X-Amz-Date=20220825T220713Z\u0026X-Amz-Expires=30\u0026X-Amz-SignedHeaders=host\u0026X-Amz-Signature=eadd10e2b543a4a829c7df970baaab478de48935601540ad702296e177de3bde","expiration":30}
```
the problem is that it's using 8576 which would be fine if the storage docker container was forwarding that port. But it's not forwarding that port `docker ps`

```
CONTAINER ID   IMAGE                                      COMMAND                   CREATED         STATUS                   PORTS                                                                                            NAMES
70b2dafe48a6   minio/minio:RELEASE.2022-07-08T00-05-23Z   "/usr/bin/docker-ent…"    9 minutes ago   Up 9 minutes             0.0.0.0:9000->9000/tcp, :::9000->9000/tcp, 0.0.0.0:49191->8484/tcp, :::49191->8484/tcp           api-hasura-boring_lehmann-minio-1
e1af6bbed239   traefik:v2.8                               "/entrypoint.sh --ap…"    9 minutes ago   Up 9 minutes             80/tcp, 0.0.0.0:1337->1337/tcp, :::1337->1337/tcp, 0.0.0.0:49192->8080/tcp, :::49192->8080/tcp   api-hasura-boring_lehmann-traefik-1
b670dabaf2cc   nhost/hasura-storage:0.2.3                 "/nix/store/qj1jhdnc…"    9 minutes ago   Up 8 minutes             8576/tcp                                                                                         api-hasura-boring_lehmann-storage-1
```

The easiest solution is to forward that port. 

The other solution is to set the env variable `public_url` env variable to http://localhost:1337 and have traefik forward that port to the storage container. 

**Expected behavior**
Presigned URL should be sent to the correct URL 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 20
 - Browser Chrome
 - Version Nhost CLI v0.7.8 for linux-amd64

**Additional context**

**Comment by plmercereau** [comment]
Maybe a missing environment variable in the container definition @elephant3 ?

**Comment by elephant3** [comment]
@acarrera94 plz upgrade to the [v0.7.9](https://github.com/nhost/cli/releases/tag/v0.7.9)

⚠️ plz read the release notes if you wanna keep your postgres data after upgrade
