### ISSUE TITLE
Incorrect pulling of migrations from remote

### ISSUE THREAD

**Issue by elitan** [nhost/cli#313]
It seems like the CLI is only pulling database **table** schemas, not other migrations like computed fields, triggers, etc., during `nhost init --remote`.

Documentation from Hasura: 
- https://hasura.io/docs/latest/migrations-metadata-seeds/migrations-metadata-setup/#step-2-set-up-a-project-directory
- https://hasura.io/docs/latest/hasura-cli/commands/hasura_migrate_create/#examples

**Comment by elitan** [comment]
When pulling SQL migrations from the server, we want to pull all migrations except the `auth` and `storage` schemas since Hasura Auth and Hasura Storage handle these two schemas.

**Comment by seyaobey-dev** [comment]
Thanks for looking into this issue. Any idea on when it could be fixed? Thanks again.

**Comment by elephant3** [comment]
This one has been fixed in recent releases. @seyaobey-dev could you confirm?
