### ISSUE TITLE
Wrong port number for mailing causes internal server error

### ISSUE THREAD

**Issue by chrtze** [nhost/cli#320]
**Describe the bug**
After upgrading the CLI and our nextjs app to the latest sdks, I encountered that the signup results in an internal server error (in local development). The error can be fixed by setting the smtp port in the config.yaml to `1025` which was 1118 before (?). I am not sure if this was happening because of our older nhost project or if this is something that needs to be fixed in the CLI.

Version: Nhost CLI v0.7.9 for darwin-arm64

**Comment by elitan** [comment]
Oh that's right. We should show a warning during startup.

If `host` is `mailhog` and `port` is not `1025`:
  print: 'Change smtp.port to 1025 to get Mailhog to work with Auth`

**Comment by elitan** [comment]
Should be fixed now.
