### ISSUE TITLE
How to attach to api logs

### ISSUE THREAD

**Issue by elitan** [nhost/cli#33]
Print how to attach to API logs

ex: `docker logs -f nhost_api_1`.

Can we control the name (`nhost_api_1`) to be sure it's correct when printing?

**Comment by elitan** [comment]
Using `container_name: <name>` sets the name. I've set the name here: https://github.com/nhost/cli/pull/32/commits/d517eec73117042e03a81dd272aef1f955327ef6

**Comment by nunopato** [comment]
@elitan looks good, will close the issue

**Comment by nunopato** [comment]
@elitan the issue is about logs, not the name of the container, sorry for closing it, reopening it..

**Comment by elitan** [comment]
Done: https://docs.nhost.io/cli/dev#logs
