### ISSUE TITLE
Initializing Nhost project locally through CLI fails

### ISSUE THREAD

**Issue by ThirusOfficial** [nhost/cli#350]
Initializing a project locally failed with the message `Failed to pull migrations from remote`

Nhost CLI version: v0.8.1

<img width="565" alt="Screenshot 2022-09-19 at 11 29 22 AM" src="https://user-images.githubusercontent.com/74656238/190961305-d64f734e-23db-4013-9bc4-6f8dfe7a8a2a.png">

Debug messages:
<img width="848" alt="Screenshot 2022-09-19 at 11 52 07 AM" src="https://user-images.githubusercontent.com/74656238/190961317-1b3c786a-3543-4e83-9314-f1c945457ad9.png">

**Comment by comontes** [comment]
I get the same error 🙁

**Comment by comontes** [comment]
```
carlos@Carloss-MacBook-Air ~ % nhost init --remote -d    
> Fetching user data
> Fetching saved auth credentials
✔ Selected: parladu  Default Workspace
> Created .nhost
> Created .nhost
> Created nhost
> Created nhost/migrations
> Created nhost/metadata
> Created nhost/seeds
> Created nhost/emails
> Created nhost/config.yaml
> Created .env.development
> Created .gitignore
> Created .nhost/nhost.yaml
> Generating app configuration
> Saving app configuration
> Cloning github.com/nhost/hasura-auth/email-templates to nhost/emails
> Writing .gitignore
> [path] Removing .nhost/nhost.yaml
> Saving app information in .nhost/nhost.yaml
> Initializing Hasura client
> [hasura] [v2.10.1] Fetching binary
> Downloading hasura cli from 'https://github.com/hasura/graphql-engine/releases/download/v2.10.1/cli-hasura-darwin-amd64'
> [darwin-arm64] Writing hasura binary
> Creating migration 'init'
> Fetching metadata
> Fetching schema list
> Clearing remote migration for source: default
> Clearing migration
> 
> fork/exec parladu/.nhost/hasura: no such file or directory

carlos@Carloss-MacBook-Air ~ % 
```

Could it be that nhost CLI is downloading cli-hasura-darwin-amd64 when it maybe should be cli-hasura-darwin-arm64 since Im on an M1 Mac?

**Comment by elephant3** [comment]
> Could it be that nhost CLI is downloading cli-hasura-darwin-amd64 when it maybe should be cli-hasura-darwin-arm64 since Im on an M1 Mac?

That will change in upcoming release. `amd64` works well on `Apple M1` if you have Rosetta installed. The error happens because of other problem - incorrect path to hasura cli, to be fixed soon

**Comment by comontes** [comment]
yep, `parladu` is the name of the project's folder
