### ISSUE TITLE
Cloning remote project has default email templates instead of custom

### ISSUE THREAD

**Issue by jovermier** [nhost/cli#357]
When running `nhost init --remote` the emails directory cloned down are all the default ones instead of the ones I have updated in the git project. I understand the project is on the free tier but I would still expect those email templates to be what I have configured in preparation to go to a paid plan.

**Comment by elitan** [comment]
If you already have a git repo setup for your Nhost project you should clone your repository, and not do `nhost init --remote`.

`nhost init` is meant to only run **once** ever of the life cycle of a Nhost project.

**Comment by jovermier** [comment]
I understand init remote isn't intended to be used frequently during development. There was an issue with the migration files in my project after upgrading the cli so I wanted to get a fresh version of the project to test.

**Comment by elitan** [comment]
Ok, that's also a valid use case.

Yea, good point. Let's keep this issue open. I also think it would make sense that the email templates would sync. However, it's not a quick fix for how we set things up in our infrastructure. Pulling migrations/metadata is easier.

**Comment by jovermier** [comment]
Yup I figured things might be a little more challenging on your side. Figured it would be good to get it on the backlog.
