### ISSUE TITLE
while i run the command i get to see this error everytime

### ISSUE THREAD

**Issue by Angryman18** [nhost/cli#364]
![Screenshot from 2022-09-25 20-08-16](https://user-images.githubusercontent.com/63530626/192191856-626bea4d-b11e-4112-80aa-90a28e74d97c.png)

**Comment by elephant3** [comment]
Hello @Angryman18

Could you please show permissions for your folder `/home/system76/Desktop/Projects` and downloaded file `cli-v0.8.1-linux-amd64.tar.gz` there?

**Comment by Angryman18** [comment]
![Screenshot from 2022-09-26 14-34-59](https://user-images.githubusercontent.com/63530626/192237247-aa02518c-98c7-48e5-8919-66401a5426c0.png)

**Comment by elephant3** [comment]
Solved by removing the `~/.nhost/hasura`
