### ISSUE TITLE
Check if entries exists before adding to .gitignore

### ISSUE THREAD

**Issue by elitan** [nhost/cli#37]
```js
    // CHECK FIRST
    // create or append to .gitignore
    const ignoreFile = `${workingDir}/.gitignore`;
    await writeFile(
      ignoreFile,
      `\n/nhost/config.yaml\n/nhost/.nhost\n/nhost/db_data\n/nhost/minio_data`,
      {
        flag: "a",
      }
    );
```

Possible move `.nhost/` folder to root of directory, and move `db_data` and `minio_data` to `.nhost/` so we only need to add `.nhost` to `.gitignore`.

**Comment by nunopato** [comment]
@elitan moving `.nhost` to the root of the project sounds good to me

**Comment by elitan** [comment]
@nunopato What about moving `db_data` ,`minio_data` to the `.nhost/` folder too? Basically everything that should not be checked in to git should be in the `.nhost/` folder is my thinking:

- `db_data`
- `minio_data`
- `nhost.yaml`

**Comment by nunopato** [comment]
@elitan yes that too, I meant with `db_data` and `minio_data` within it 👍

**Comment by nunopato** [comment]
this issue can be closed since this is already implemented 👍
