### ISSUE TITLE
How to get user details in a custom function?

### ISSUE THREAD

**Issue by FostersData** [nhost/cli#372]
It looks like custom functions are just a plain Lambda function without any of the Nhost context. Is there a way to get the current user etc?

What I'm looking for is to call the custom function from the frontend, with a logged-in user in the client. I'll check the user's email against a whitelist and then proxy the request through to a separate backend which can query our DB.

If this isn't possible then I can work around it without using Nhost's custom functions (will use the Azure auth library and send that token directly to our API) but would be a cleaner UX to just log in once and have the backend take care of the rest!

**Comment by elitan** [comment]
Maybe this can help you:

Get the authenticated user in a Serverless Function

https://github.com/nhost/nhost/discussions/278

**Comment by FostersData** [comment]
That gives the user ID, but can do a step better by hitting the Hasura Auth endpoint to get user details (just send the access token as a bearer token in the `Authorization` header). OpenAPI docs [here](https://editor.swagger.io/?url=https://raw.githubusercontent.com/nhost/hasura-auth/main/docs/openapi.json) and go to `/user` endpoint
