### ISSUE TITLE
Running in a GitHub Action

### ISSUE THREAD

**Issue by altschuler** [nhost/cli#378]
## EDIT: Turns out this is only an issue when running locally using [act](https://github.com/nektos/act). Feel free to close if this isn't something you consider an issue with nhost cli (it probably isn't), but leaving open for the nhost team to decide.

Hi, I'm trying to run the local Nhost setup in a GitHub action (for testing), but am having issues during start. 

Below is the command and output, note I had to install hasura cli and set the arg explicitly, otherwise there were permission errors:

```
root@slaptop:/path/to/project# nhost up --no-browser --hasuracli hasura

> Starting functions...          
> Failed to start services
> [exit status 1
Network backend-sweet_chebyshev_default  Creating
Network backend-sweet_chebyshev_default  Created
Container backend-sweet_chebyshev-functions-1  Creating
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /path/to/project
] Failed to start services
```

I believe it's an issue with running docker in docker, but I don't know how to fix or debug it since the CLI spins up the containers automatically.

Maybe it'd work to run the docker file from https://github.com/nhost/nhost/blob/main/examples/docker-compose/docker-compose.yaml manually, but using the CLI will ensure consistency and reproducibility.

I saw https://github.com/nhost/cli/issues/80, but seems a solution wasn't found, and I'm using `v0.8.3`. Also worth noting that this is running in [act](https://github.com/nektos/act).

**Comment by elephant3** [comment]
Which docker version do you use?

**Comment by altschuler** [comment]
> Which docker version do you use?

`Docker version 20.10.17, build 100c70180f`
