### ISSUE TITLE
error while trying to init project

### ISSUE THREAD

**Issue by dandiasd** [nhost/cli#382]
I got an error while trying to 
`nhost init --remote`
error : 
`Failed to initialize Hasura client`

**Comment by elitan** [comment]
Would you mind trying again with the latest version?

```
sudo nhost upgrade
```

**Comment by elephant3** [comment]
Seems to be a dup of https://github.com/nhost/cli/issues/350
AFAIK still an issue, investigating

**Comment by dandiasd** [comment]
actually this issue is done , I can create the nhost project now, I raised in discord like 1 month ago.

**Comment by elitan** [comment]
@dandiasd If this was resolved, feel free to close this issue 🙏

**Comment by dandiasd** [comment]
alright , thankss!
