### ISSUE TITLE
Port 9695 is not available

### ISSUE THREAD

**Issue by marcusrohden** [nhost/cli#383]
Hi, I'm not being able to start my local dev env

```
marcusrohden@Marcuss-MBP tribe-end % nhost dev up
> Failed to start services
> [port 9695 is not available, use --console-port flag to provide another one] Failed to start services

```

Nhost CLI v0.8.3 for darwin-amd64
Docker version 20.10.17, build 100c701

**Comment by szilarddoro** [comment]
Hey @marcusrohden! It's possible that `nhost dev` didn't exit properly and something keeps using that port.

Could you please try running the following command in your terminal to see what is using that port?
```sh
lsof -nPi | grep 9695
```

You can kill the process using that port, then run `nhost dev` again.

**Comment by elephant3** [comment]
looks like `hasura console` is running, check in `Activity Monitor` by querying `hasura`
