### ISSUE TITLE
Feature request: Add a "don't quit on error" flag to the CLI so the containers are not stopped in case of an error

### ISSUE THREAD

**Issue by kratam** [nhost/cli#384]
Use-case: In case of inconsistent metadata, the CLI quits immediately, preventing the developer from solving the issue right away (e.g. by fixing the table in the DB).

**Comment by plmercereau** [comment]
Yes, we can't understand why a container failed to start. Not necessarily a flag but at least a means to get the logs of the failed container.
Maybe to print the container log to stdout
