### ISSUE TITLE
Running nhost dev/up, got "no container found for project ..."

### ISSUE THREAD

**Issue by cipto-hd** [nhost/cli#392]
I had followed this tutorial step by step, https://dev.to/nhost/nhost-cli-from-zero-to-production-220h

but after running `nhost dev`, got this error:
![nhost dev/up error](https://user-images.githubusercontent.com/5018833/194988952-5ff4c5bb-a8c6-416d-ad75-5d33d9be2239.png)

By the way, my desktop OS is Ubuntu 22.04 and I found out that error `no container found for project "sample_app-ecstatic_haibt": not found`, the name is on traefik section config as shown below:
![traefik config](https://user-images.githubusercontent.com/5018833/194990517-462deb4b-d399-495a-810f-7a183e616118.png)

## Nhost CLI version
![nhost cli version](https://user-images.githubusercontent.com/5018833/194989590-4f2e674e-986b-491e-ba28-ae256e84704e.png)

## Docker version
![docker version](https://user-images.githubusercontent.com/5018833/194989468-4f6bd362-6418-4336-9025-92d4edff9d4f.png)

Any help would very appreciated. Thank you in advance

**Comment by cipto-hd** [comment]
now It turns out that nhost up/dev needs sudo. solved

**Comment by elitan** [comment]
You shouldn't have to use `sudo` when doing `nhost up/down`. It might be that your permissions for docker might be adjusted. 

Here's an article on how to use docker as a non-root user:

https://docs.docker.com/engine/install/linux-postinstall/

**Comment by cipto-hd** [comment]
Thank you for the info, i'll check it soon. Very appreciated
