### ISSUE TITLE
nhost dev fails with --graphql-port

### ISSUE THREAD

**Issue by beepsoft** [nhost/cli#398]
I'm running the latest nhost on M1 mac with Docker Desktop 4.12.0

```
> nhost version
> Nhost CLI v0.8.3 for darwin-amd64
> You have the latest version. Hurray!
```

I try to create a new project and run it with Hasura running on a user specified port but startup fails like this: 
```
> nhost init
✔ Name of your new app: new_project3█
> Successful! Start your app with `cd new_project3 && nhost dev`
(base) [me@host:~/tmp/nhost3]
> cd new_project3/
(base) [me@host:~/tmp/nhost3/new_project3]
> nhost dev -d --graphql-port 8850

> Initializing Hasura client
> start timeout is set to 10m0s
> Stopping docker compose
> Starting docker compose
> Starting functions
> Starting postgres, graphql-engine containers...
> Waiting for graphql-engine service to be ready
> Waiting for all containers to be up and running
> [exit status 1
Container new_project3-blissful_northcutt-minio-1  Creating
Container new_project3-blissful_northcutt-storage-1  Creating
Container new_project3-blissful_northcutt-traefik-1  Creating
Container new_project3-blissful_northcutt-mailhog-1  Creating
Container new_project3-blissful_northcutt-functions-1  Running
Container new_project3-blissful_northcutt-postgres-1  Running
Container new_project3-blissful_northcutt-graphql-engine-1  Running
Container new_project3-blissful_northcutt-auth-1  Creating
Container new_project3-blissful_northcutt-storage-1  Created
Container new_project3-blissful_northcutt-traefik-1  Created
Container new_project3-blissful_northcutt-auth-1  Created
Container new_project3-blissful_northcutt-mailhog-1  Created
Container new_project3-blissful_northcutt-minio-1  Created
Container new_project3-blissful_northcutt-minio-1  Starting
Container new_project3-blissful_northcutt-minio-1  Started
Error response from daemon: dial unix docker.raw.sock: connect: connection refused
] Failed to wait for running/healthy services
> Start took 22.272651834s


> [exit status 1
Container new_project3-blissful_northcutt-minio-1  Creating
Container new_project3-blissful_northcutt-storage-1  Creating
Container new_project3-blissful_northcutt-traefik-1  Creating
Container new_project3-blissful_northcutt-mailhog-1  Creating
Container new_project3-blissful_northcutt-functions-1  Running
Container new_project3-blissful_northcutt-postgres-1  Running
Container new_project3-blissful_northcutt-graphql-engine-1  Running
Container new_project3-blissful_northcutt-auth-1  Creating
Container new_project3-blissful_northcutt-storage-1  Created
Container new_project3-blissful_northcutt-traefik-1  Created
Container new_project3-blissful_northcutt-auth-1  Created
Container new_project3-blissful_northcutt-mailhog-1  Created
Container new_project3-blissful_northcutt-minio-1  Created
Container new_project3-blissful_northcutt-minio-1  Starting
Container new_project3-blissful_northcutt-minio-1  Started
Error response from daemon: dial unix docker.raw.sock: connect: connection refused
] Failed to start services
> Stopping docker compose
(base) [me@host:~/tmp/nhost3/new_project3]
```

If I run without `--graphql-port` it starts OK. (Interestingly, if I run with `--graphql-port 8888` it starts OK as well. But it won't start with any other port I tried)

**Comment by elitan** [comment]
Would you mind looking at the logs `nhost logs -f` while starting Nhost? There might be a clue there.

**Comment by beepsoft** [comment]
Nothing really helpful there:

<img width="1601" alt="image" src="https://user-images.githubusercontent.com/1926265/195503329-7a6534a2-b4fd-4071-9bdd-e99138d66643.png">

Sometimes postgres seems to start up and then fails.

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/1926265/195505462-e230983a-b95b-4508-8a1d-9f395d5dcaa4.png">


I checked that I have enough resources configured for Docker (6 cpus, 20G memory, 100G disk space) and it works OK with other docker-compose projects.

**Comment by beepsoft** [comment]
I don't know if it is related, but now I tried on an Intel mac and after `nhost init` it fails to start even without `--graphql-port`:

```
> nhost dev

You are using 20.10.13 version of docker engine. Please upgrade to 20.10.17 or higher version.
Upgrade instructions: https://docs.docker.com/engine/install/


> Failed to start services
> [exit status 1
no such service: hasura
] Failed to start services
```

`nhost logs -f` shows nothing here.

**Comment by beepsoft** [comment]
On Intel Mac for me 0.6.14 is the latest, which works. v0.7.1 and above fails with this `no such service: hasura` message. I removed all hasura images and updated my hasura cli as well, just in case.

**Comment by beepsoft** [comment]
On Intel I updated docker and now it works fine, sorry about that. I will see if it helps on my M1 machine, although there I already had the latest version.

**Comment by beepsoft** [comment]
What I can conclude is that it happens randomly on M1 with Docker version 20.10.17, build 100c701.

I tried running the same `nhost dev -d --graphql-port 8850` command over and over again and sometimes it starts OK, sometimes it stops with `Error response from daemon: dial unix docker.raw.sock: connect: connection refused`. Then if I change the port: it either starts all right or fails with the same error.

One thing I noticed is that nhost's traefik container maps `/var/run/docker.sock` as a volume. May this effect this?

**Comment by dnk8n** [comment]
> > Failed to start services
> > [exit status 1
> no such service: hasura
> ] Failed to start services

I reliably get this same error message on Intel / Linux (Ubuntu 22.04) on v0.8.15 of nhost.

`docker compose -f ./.nhost/docker-compose.yaml up -d --build` works.

If I run `nhost up -d` I get:

```
> Initializing Hasura client
> start timeout is set to 10m0s
> Stopping docker compose
> [exit status 1
no such service: hasura
] Failed to stop functions service


> [exit status 1
no such service: hasura
] Failed to start services
> Stopping docker compose
> [exit status 1
no such service: hasura
] Failed to stop functions service
```

**Comment by elitan** [comment]
Was this issue fixed by https://github.com/nhost/cli/pull/511 ?
