### ISSUE TITLE
Handle ports already in use

### ISSUE THREAD

**Issue by elitan** [nhost/cli#4]
if, ex, port 8080 is already in use `nhost dev` will crash:

```
╭─elimbp ~/tmp/nhost/facebook2
╰─➤  nhost dev
Error: Command failed: docker-compose up -d > /dev/null 2>&1
    at DevCommand.run (~/projects/nhost/cli/src/commands/dev.js:42:5)
    at DevCommand._run (~/projects/nhost/cli/node_modules/@oclif/command/lib/command.js:44:31)
```

We should handle this by either, generate a new port to use or exit and prompt with a message saying why `nhost dev` won't work.

I think V1 could just exit and say the ports are already in use.

**Comment by nunopato** [comment]
Current behaviour: the CLI outputs a warning message asking the user to double check if all ports configured in `config.yaml` are available.

**Comment by elitan** [comment]
We can use [`detect-port`](https://www.npmjs.com/package/detect-port) to check if all ports ara available before starting the services.

**Comment by elitan** [comment]
We now check for ports on `nhost dev`.
