### ISSUE TITLE
Add Postgres extensions (if possible)

### ISSUE THREAD

**Issue by csterritt** [nhost/cli#43]
I have a Postgres extension installed in my official database, `pg_trgm`, which wasn't found by the CLI's migration generator.  This may not be possible, or it may be a Hasura thing, so I'd be glad to post a request there.

Anyway, adding

``` sql
CREATE EXTENSION IF NOT EXISTS pg_trgm;
```

To my migration's `up.sql` file cleared up the problem, and the project was able to start.

The code that uses the extension, which (as we found) kills the seeding of the auth.roles, etc., is:

``` sql
CREATE FUNCTION public.search_recipe(search text) RETURNS SETOF public.recipe
    LANGUAGE sql STABLE
    AS $$
SELECT   *
FROM     recipe
WHERE    search <% ( name || ' ' || tags || ' ' || coalesce(notes, '') || ' ' || coalesce(cookbook, '') )
ORDER BY similarity(search, ( name || ' ' || tags || ' ' || coalesce(notes, '') || ' ' || coalesce(cookbook, '') )) DESC;
$$;
```

The `<%` is non-standard syntax, and fails.

This may help writing a test.

**Comment by elitan** [comment]
Relevant:

```sql
SELECT * FROM pg_extension
```
