### ISSUE TITLE
Hasura Doesn't Stop With `nhost down`

### ISSUE THREAD

**Issue by linden** [nhost/cli#432]
I've found that hasura will continue to run even after `nhost down`. this will prevent you from stopping then starting a instance. from what I've noticed this seems to happen every time (even on the latest version, `v0.8.6`). I've found a work-around I've been using for a while (`nhost down && pkill hasura`). I'd recommend either adding `pkill hasura` when `nhost down` is run or moving hasura into a docker container so it can be isolated and managed like all the other services (which would also make the CLI more portable).

**Comment by elephant3** [comment]
Could you please check if the problem remains on the latest release?

**Comment by linden** [comment]
sorry for the delay @elephant3, I didn't run into this initially but this still happens occasionally but now doesn't throw an error in the console it just fails silently (even with `-d`), you need to dig into `nhost logs` now.

**Comment by shubhamsinghshubham777** [comment]
I'm facing the same issue (i.e. having to force close `hasura` task from Activity Monitor every time)

**Comment by dbarrosop** [comment]
this shouldn't be an issue anymore in the new CLI
