### ISSUE TITLE
`nhost up` does not work in wsl2

### ISSUE THREAD

**Issue by Cactu5** [nhost/cli#460]
Nhost CLI version: `Nhost CLI v0.8.11 for linux-amd64` on **wsl2**.
Docker version: `Docker version 20.10.21, build baeda1f`
Ubuntu version: `Ubuntu 20.04`

I initiated the project by doing
`nhost init --remote`
cd into the directory and then run `nhost up`.

It then fails with:
```
> Starting functions...                                                                                                 
> Failed to start services                                                                                              
> [exit status 1                                                                                                        
Container comic-website-sweet_hugle-postgres-1  Creating                                                                
Container comic-website-sweet_hugle-postgres-1  Created                                                                 
Container comic-website-sweet_hugle-graphql-1  Creating                                                                 
Container comic-website-sweet_hugle-graphql-1  Created                                                                 
Container comic-website-sweet_hugle-postgres-1  Starting                                                               
Container comic-website-sweet_hugle-postgres-1  Started                                                                 
Container comic-website-sweet_hugle-postgres-1  Waiting                                                                
container for service "postgres" is unhealthy                                                                           ] 
Failed to start services
```

[See full log here](https://pastebin.com/m77mAYAN)

It seems like there's some sort of permissions issue:
`initdb: error: could not change permissions of directory "/var/lib/postgresql/data/pgdata": Operation not permitted`

Folder permissions:
```
drwxrwxrwx 1 cactus cactus 512 Nov 27 20:02 .
drwxrwxrwx 1 cactus cactus 512 Nov 27 12:23 ..
-rwxrwxrwx 1 cactus cactus   0 Nov 27 12:23 .env.development
-rwxrwxrwx 1 cactus cactus  59 Nov 27 12:23 .gitignore
drwxrwxrwx 1 cactus cactus 512 Nov 27 20:02 .nhost
drwxrwxrwx 1 cactus cactus 512 Nov 27 12:29 functions
drwxrwxrwx 1 cactus cactus 512 Nov 27 12:23 nhost
drwxrwxrwx 1 cactus cactus 512 Nov 27 12:29 node_modules
```

Folder permissions inside `.nhost`:
```
drwxrwxrwx 1 cactus cactus   512 Nov 27 20:02 .
drwxrwxrwx 1 cactus cactus   512 Nov 27 20:02 ..
drwxrwxrwx 1 cactus cactus   512 Nov 27 20:02 custom
drwxrwxrwx 1 cactus cactus   512 Nov 27 20:02 data
-rwxrwxrwx 1 cactus cactus 13772 Nov 27 20:02 docker-compose.json
-rwxrwxrwx 1 cactus cactus    24 Nov 27 20:02 project_name
```

Folder permissions of `.nhost/data/main/db/pgdata`:
`drwxrwxrwx 1 cactus cactus 512 Nov 27 20:02 pgdata`

I don't know how to fix this, help is appreciated! 🙂

**Comment by elephant3** [comment]
@nunopato could you assist? ^

**Comment by Einlar** [comment]
I have just tried it on WSL2 (Ubuntu 22.04) and it works for me without issue:

```console
$ nhost version
> Nhost CLI v0.8.24 for linux-amd64
$ docker --version
Docker version 20.10.23, build 7155243
```

I installed it with `nhost init`, then run with `nhost up`.

**Comment by phlogios** [comment]
I have the same error, on WSL2

**Comment by Matheswaaran** [comment]
I fixed the error by adding the following lines to `/etc/wal.conf` in the wsl2 ubuntu.

```bash
[automount]
options = "metadata"
```

Now, Restart the windows and try `nhost up`.

**Comment by gokulramtj** [comment]
> I fixed the error by adding the following lines to `/etc/wsl.conf` in the wsl2 ubuntu.
> 
> ```shell
> [automount]
> options = "metadata"
> ```
> 
> Now, Restart the windows and try `nhost up`.

Thanks @Matheswaaran. It works like magic!

I also looked into this and here's credits to the source
https://github.com/nhost/cli/issues/460#issuecomment-1597779642

**Comment by dbarrosop** [comment]
Thanks to everybody for helping nailing down this issue!
