### ISSUE TITLE
Feature request: add a way for cli to programmatically set environment variables 

### ISSUE THREAD

**Issue by spakanati** [nhost/cli#465]
It is currently difficult to keep nhost in sync with environment variables in other services we use. When our environment variables change we are able to update all other services programmatically except nhost, which requires manual configuration in the dashboard.

It would be very useful to have some way to programmatically set env vars for the cloud projects. This could be either the cli or some other method, but since there is already `nhost env list` and `nhost env pull` the cli seems like it could be a natural choice for `nhost env set key value` or similar.

The only complication is that `nhost env list` only uses the linked project, and you would need to be able to set environment variables for any nhost project, not just the currently linked project. (Although nhost can only link to one project at a time for the `env` commands, many users have multiple branches set up with Github for different nhost projects on different environments).

**Comment by dbarrosop** [comment]
hi, sorry for the delay. I just wanted to double check if this was still an issue for you or if you had managed to solve this problem somehow.

**Comment by dbarrosop** [comment]
that makes sense, thx for the feedback

**Comment by dbarrosop** [comment]
@spakanati I remember we talked out of band about batch updates of secrets but, are you missing something else besides that?
