### ISSUE TITLE
nhost up failed to check docker version in Ubuntu 22.04 with Docker Desktop installed

### ISSUE THREAD

**Issue by rvalledorjr** [nhost/cli#471]
Had a private nhost project repo created initially in Mac: no problem there. But when I started running `nhost up` on the same repo but on an Ubuntu machine, it throws the following error:

```
> failed to check docker version, make sure it's running: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? 
```

I have Docker Desktop for Linux installed and its running when I invoked `nhost up`.

I don't have a Docker engine installed.

**Comment by rokal** [comment]
I am on ubuntu and I am not able to start nhost using `nhost up`

**Comment by fresheneesz** [comment]
I'm using WSL2 on Ubuntu 22 and I'm getting the same thing. `docker --version` gives me `Docker version 20.10.22, build 3a2c30b` so I'm not sure why its failing to check the docker version.
