### ISSUE TITLE
Error on nhost up: manifest for hasura/graphql-engine:v2.15.1 not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by rvalledorjr** [nhost/cli#484]
Ran `nhost up` and received the following error:

```cli
graphql Error 
Error response from daemon: manifest for hasura/graphql-engine:v2.15.1 not found: manifest unknown: manifest unknown
] Failed to start services
```

I also tried docker pulling `hasura/graphql-engine:v2.15.1` directly, and got the same error as above.

I wonder if v2.15.1 was dropped due to a "critical security vulnerability" as written in v2.15.2's [change log here](https://github.com/hasura/graphql-engine/releases/tag/v2.15.2)

https://github.com/nhost/cli/blob/73c3f48cd6d372a81cee2d0bbe38da931358ca9b/nhost/compose/config.go#L45

**Comment by elephant3** [comment]
@rvalledorjr please get the latest fresh CLI release v0.8.12 with fixed version. Yes, hasura for some reason removed 2.15.1 docker image from docker hub 🤷‍♂️
