### ISSUE TITLE
Add user claims

### ISSUE THREAD

**Issue by elitan** [nhost/cli#49]
Be able to specify custom user claims from the `users` table in the JWT token.

**Comment by nomocas** [comment]
+1. Top priority.

**Comment by elitan** [comment]
I've added the details here on how to add custom permission variables in our documentation: https://docs.nhost.io/cli/dev#configuration

This is what I wrote:

------

### Permission variables

To add permission variables to the JWT token set `JWT_CUSTOM_FIELDS` in `.env.development`.

Example: if every user has a `company_id` column that should be used as a permission variable in the JWT token (`x-hasura-company-id`):

```bash:.env.development
JWT_CUSTOM_FIELDS=company_id
```
