### ISSUE TITLE
"Open Hasura" on the Dashboard does not appear to use --console-port

### ISSUE THREAD

**Issue by mainstreetmark** [nhost/cli#517]
If I start nhost, locally, via:

`/usr/local/bin/nhost dev --ui nhost --port 9009 --console-api-port 9001 --console-port 9002 --dashboard-port 9003 --db-port 9004 --graphql-port 9005 --mailhog-port 9006 --minio-s3-port 9007 --smtp-port 9008`

I would expect Hasura to be running on :9002.  In fact, according to the command's output, it is running on :9002.

```
> Ready to use

URLs:
- Postgres:             postgres://postgres:postgres@localhost:9004/postgres
- GraphQL:              http://localhost:9009/v1/graphql
- Auth:                 http://localhost:9009/v1/auth
- Storage:              http://localhost:9009/v1/storage
- Functions:            http://localhost:9009/v1/functions

- Nhost Dashboard:      http://localhost:9003
- Hasura Console:       http://localhost:9002
- Mailhog:              http://localhost:9006

- subdomain:            localhost
- region:               (empty)
```

However, on the Dashboard (at :9003), on the Hasura tab, the "Open Hasura" button opens to port :9695, the default port.

**Comment by dbarrosop** [comment]
Closing as this may not be relevant anymore, feel free to reopen otherwise
