### ISSUE TITLE
flag 'data' is known when using nhost down --data   

### ISSUE THREAD

**Issue by vipafattal** [nhost/cli#573]
**Describe the bug**
When using the flag 'data' to clear containers data I got an error: unknown flag: --data

**To Reproduce**
Use [nhost down --data](https://docs.nhost.io/reference/cli/down) as described in docs

**Desktop:**
 - OS: WSL2 Ubuntu 20.04.5 LTS
 - Version  Nhost CLI v0.8.21 for linux-amd64

**Comment by joshuadutton** [comment]
I want to bring more attention to this issue. Re-running all migrations with a clean database is a core part of my development process. It really threw me off that my data was persisting, even after I deleted all the Docker volumes. I now know to delete the database cache in the `.nhost` directory, but I would really appreciate it if this feature worked.
