### ISSUE TITLE
Suggestion: `nhost pull` to fetch server changes to local environment

### ISSUE THREAD

**Issue by siniradam** [nhost/cli#599]
Having an additional command to fetch changes made on web interface to local environment  is a required feature in my opinion.
NHost provides interfaces like hasura, we should be able to fetch changes to locan environment.

Since there is no `nhost init --remote ./` option (nhost init --remote creates a folder) only way to achieve this is creating a new project folder than copying nhost files to local project directory.

Either `nhost init --remote ./` or `nhost pull` would help with this.

**Comment by dohomi** [comment]
agree on this. It would be great to merge remote changes to local changes additionally to sharing the git repo

**Comment by dbarrosop** [comment]
Apologies, this one fell through the cracks. Unfortunately this isn't technically possible currently. Hasura doesn't create migrations, you need an extra service for that and then you need to route the console and other API requests through it. Deploying this extra service is something we do in the CLI but we don't in the cloud as it'd have an impact on the service performance as some requests would've to be re-routed through an extra hop. Additionally, this service requires a decent amount of memory to run so it'd have a negative impact as there would be less memory available for the production services.

With enough interest we could **consider** this as a paid addon or similar but we believe this would encourage bad development practices and make the overall development workflow more complex and error-prone.
