### ISSUE TITLE
Nhost CLI won't start: "ports.0.published must be a integer"

### ISSUE THREAD

**Issue by remaininlight** [nhost/cli#607]
Hey all, having some issues with Nhost putting quotes around 'published' ports in the docker compose file it renders

When I run:
```
nhost up
```
It gives this error:
```
> [exit status 15
services.traefik.ports.0.published must be a integer
] Failed to start services
> Stopping docker compose
```
Here are my versions of Nhost and Docker:
```
$ docker-compose version
Docker Compose version 2.13.0
$ nhost version
> Nhost CLI v0.8.23 for darwin-arm64
> You have the latest version. Hurray!

Docker Desktop version:
4.16.2
Compose within Docker Desktop:
2.15.1
```

I had this problem before and put in this pull request:
https://github.com/nhost/cli/pull/459
Unfortunately @elephant3's PR here (https://github.com/nhost/cli/pull/472) hasn't fixed the issue for me. Had been working from my fork for a while but now I've had to upgrade and the issue's back

If anyone has any tips or pointers as to what I might be doing wrong that would be much appreciated!

**Comment by remaininlight** [comment]
Using this workaround at the moment:
```
$ nhost up
# Remove all the quotes on lines with 'published' in them
$ sed -i -e '/published:/s/"//g' ./.nhost/docker-compose.yaml
$ docker compose -f ./.nhost/docker-compose.yaml up -d --build
```

**Comment by elephant3** [comment]
Hi @remaininlight, thx for reporting this. It's so weird that it's still happening. Did you try to update Docker for mac to the latest version? I'm on `4.16.2` (build 95914) and not experiencing anything like that. Anyway, I made a note for myself that on some versions it's still a problem and will definitely address that.
