### ISSUE TITLE
local .env.development is not updated when adding new variables in nhost console

### ISSUE THREAD

**Issue by Svarto** [nhost/cli#62]
The local environment does not update or pull the new environment variables if already set up when the environment variable is added in the nhost console.

Trying to delete the .env.development to force a refresh on `nhost dev` makes the command not work as it can't find .env.development.

Would be great if `nhost dev` pulls the latest environment variables from nhost cloud on start, and deletes itself (similar to .nhost/) when turning off. As the environment variables can contain secrets that we do not want to push to github, but only use temporarily as we develop locally.

**Comment by elitan** [comment]
I suggest we introduce `nhost env pull` that will:

1. Remove existing env vars in .env.development.
2. pull env vars from the Nhost project and update .env.development

**Comment by Svarto** [comment]
That makes sense and allows for local testing. It would add a step when collaborators clone a git repository to also run nhost env pull. I would add to what you say and suggest that if .env.development does not yet exist, it automatically pulls the remote version. If it exists, it is only updated with the command you mentioned.

Then it can be added to .gitignore and when collaborators come on board it's a smooth git clone && nhost dev process.

-------- Original Message --------

**Comment by elitan** [comment]
> if .env.development does not yet exist, it automatically pulls the remote version. If it exists, it is only updated with the command you mentioned.

Perfect 👍
