### ISSUE TITLE
Default Docker Location Has Moved On MacOS (Causes `nhost up` To Fail)

### ISSUE THREAD

**Issue by linden** [nhost/cli#637]
Hi,

currently the cli points to `unix:///var/run/docker.sock` on macOS but in docker >= 4.13.0 that symlink has been removed, you should instead point at `~/Library/Containers/com.docker.docker/Data/docker.raw.sock`.

a temporary fix would be to just manually create a symlink as detailed here: [stackoverflow.com/a/74148162](https://stackoverflow.com/a/74148162).

**Comment by bensleveritt** [comment]
It's also possible to enable the old socket by setting `Settings > Advanced > Expose default Docker socket` to true

![20230502074139](https://user-images.githubusercontent.com/390779/235597423-a48dfa29-4311-42c6-9a79-bf5a6cba81ec.png)

**Comment by dbarrosop** [comment]
Thanks for reporting this, we will take a look as soon as possible.

**Comment by cjam** [comment]
> It's also possible to enable the old socket by setting `Settings > Advanced > Expose default Docker socket` to true
> 
> ![20230502074139](https://user-images.githubusercontent.com/390779/235597423-a48dfa29-4311-42c6-9a79-bf5a6cba81ec.png)

I had to cycle this setting as it was already true on my system, but for some reason the socket wasn't being created by the docker engine.

**Comment by dbarrosop** [comment]
This shouldn't be a problem with the latest cli. Feel free to reopen otherwise.
