### ISSUE TITLE
`nhost init` with custom project directory

### ISSUE THREAD

**Issue by szilarddoro** [nhost/cli#644]
## Use-case

We usually work with other tools as well to bootstrap projects. Let's assume that we have already created a Next.js frontend application using `create-next-app my-app`. We want to place the `nhost` folder (and everything else that's needed for it to work) in the root folder.

The desired structure:

```
my-app/
├── nhost/              # Nhost backend
├── src/                # Next.js application
├── package.json
├── .env.development
└── .gitignore
```

The contents of the `.gitignore` / `.env.development` files - given that they already exist - should be merged with the files the Nhost CLI generates.

## Problem

At the moment, it's impossible to specify a custom project directory when running the `nhost init` command. We are always prompted to give a name to the project. If you specify an already existing path (e.g: `my-app` for the previous scenario) as the project name, you get the desired structure, but if you're already inside the `my-app` folder and you run the command, you get this structure:

```
my-app/
├── my-app/
│   ├── nhost/              # Nhost backend
│   ├── .gitignore
│   └── .env.development
├── src/                    # Next.js application
├── package.json
└── .gitignore

```

## Proposal

Being able to specify the path (therefore the name) would be a great way to tackle this issue.

`$ nhost init [optional-path]`

This is how `create-next-app` works:

```bash
# Asks for the name of the app, creates a folder with the kebab case name of the app, and puts
# the generated files in that folder
$ create-next-app

# Doesn't ask for the name, creates a my-app folder, and puts the generated files in that folder
$ create-next-app my-app 

# Doesn't ask for the name, uses the name of the folder to determine it. Puts the generated files
# in the specified folder. The dot character can be replaced with any valid path.
$ create-next-app . 
```

**Comment by dbarrosop** [comment]
this should not be an issue anymore as the new cli initializes in the current folder.
