### ISSUE TITLE
Share local db in nhost

### ISSUE THREAD

**Issue by pedromontanes** [nhost/cli#656]
Hi,
We have a nhost pro account and we want to test in local with different members, we use cli nhot dev and it works but we want to modify the local postgresql db... (we want to use a external postgresql )...
The idea is to manage 2 db one real in nhost server and other fake in other server but share with different test users (all developers with access to the repository).
The different users manage local nhost dev but pointing to the same postgres, and all the developers could test the same db.

**Comment by dbarrosop** [comment]
Thanks for the request, we will take this in consideration but it may take some time. Alternatively, I'd suggest the following alternative:

1. `nhost dev` works as today. You could use seeds to insert data into the development environment to be used for tests locally. Devs can share those seeds in github as part of the automated tests.
2. you could have a staging branch that pushes to a staging environment. Here you can run end to end tests periodicaly or after a PR is merged into main
3. finally, when staging is ready you can open a PR between staging and main and merge and deploy to production

This has lower chances of developers interfering with each other as multiple developers manipulating the same database and metadata can and will cause problems very quickly (i.e. if a developer modifies a column the rest of the developers will all of a sudden have inconsistent metadata)
