### ISSUE TITLE
Ability to open containers to the public

### ISSUE THREAD

**Issue by kratam** [nhost/cli#710]
Use case: the user uploads a file to the storage service. I use an external API to scan this image. So I have to generate a presigned url and pass it to the external API, which downloads the image, scans it and returns a json.
I don't have a local version of this external API, so I have to change the presigned url to an url which can be accessed over the internet.

For this to work, I need a local port which I can open to the internet for every container (and not just a URL like https://local.storage.nhost.run/ ).

**Comment by dbarrosop** [comment]
Could you test this development version?

https://github.com/nhost/cli/actions/runs/5178430285?pr=716

You will need to pass `--storage-port 9876` to expose the storage on that port so you can tunnel it

**Comment by kratam** [comment]
Sure, hi can I install it?

**Comment by dbarrosop** [comment]
You can download the version for your platform, uncompress and run it with `/path/to/cli up`. If you are on macos you may need to run first `xattr -c /path/to/cli`

**Comment by kratam** [comment]
Tested, works perfectly.
