### ISSUE TITLE
update from 0.9.7 to 1.0.5 broke project completely without warning

### ISSUE THREAD

**Issue by israelidanny** [nhost/cli#720]
it's not immediately clear to me what to do so that I don't wreck my project and metadata.

the config no longer works:
```
main.go:59: failed to parse config: failed to open file: open nhost/nhost.toml: no such file or directory
```

`nhost up` doesn't run:
main.go:59: no nhost project found, please run `nhost init` or `nhost config pull`

And I looked a lot but couldn't find any specific migrations steps.

**Comment by israelidanny** [comment]
Ok, just found this and tried to follow it:
https://docs.nhost.io/cli/migrate-config

```
➜  hasura git:(main) nhost config pull
main.go:59: failed to get app info: failed to find app with subdomain: local
➜  hasura git:(main) nhost up
main.go:59: no nhost project found, please run `nhost init` or `nhost config pull`
```

Doesn't work.

**Comment by israelidanny** [comment]
Ok, struggling slowly to move. Apparently I had to run:
`nhost config pull --subdomain MY_LINKED_SUBDOMAIN`

It should have been the default, but that didn't work I guess? ... moving on. Now running `nhost up` gives me this error:
```
failed to generate docker-compose.yaml: hasura version must be at least v2.18.0
- Do you want to stop Nhost's development environment? [y/N]
```

**Comment by israelidanny** [comment]
So, in the end things worked out but I can't say it was easy. At all.
As feedback: It would be nice if much clearer migration guides were accompanying major changes.

**Comment by marcusrohden** [comment]
hey @israelidanny  can you please describe how did you make it work? I'm going through the same issue right now.

**Comment by israelidanny** [comment]
> hey @israelidanny  can you please describe how did you make it work? I'm going through the same issue right now.

The no project found goes away if your force a specific subdomain.
