### ISSUE TITLE
Nhost up not applying seeds on first run

### ISSUE THREAD

**Issue by st3phan** [nhost/cli#735]
### Bug description
Running `nhost up` for the first time does not apply seeds.

According to https://docs.nhost.io/database#seed-data they should be applied:
> When you're running nhost up for the first time, seed data is added.

Adding the `apply-seeds` flag however does apply the seeds:
`nhost up --apply-seeds true`

### How to reproduce
* Remove `.nhost` folder
* Run `nhost up`

### CLI version
1.2.0

**Comment by dbarrosop** [comment]
thanks for reporting this. I will release the fix tomorrow.
