### ISSUE TITLE
Per-branch data no longer being created by cli 

### ISSUE THREAD

**Issue by spakanati** [nhost/cli#757]
Under `.nhost/data` I no longer have folders for each of my git branches. Instead, I only have a `nogit` folder.

I've tried deleting the `.nhost` folder and running `nhost down` and `nhost up` on main and on other branches, but no new folders are created. Per discussion with Nuno and David in Discord, this may be a bug with the cli. This is in a Git repository that has not changed and has been connected for many months to 2 different cloud projects (and that deploys config and changes successfully). 

Cli version: v1.5.2

**Comment by dbarrosop** [comment]
Thanks for reporting, should be fixed in the next release.
