### ISSUE TITLE
graphql-engine server failed   x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by hencaz** [nhost/cli#767]
Hi,
I'm using Nhost CLI, and without any reason I would be aware of I started to have this problem when doing nhost up.
The error says:
```
ERRO connecting to graphql-engine server failed   
FATA[0000] making http request failed: Get "https://local.hasura.nhost.run/v1/version": x509: certificate has expired or is not yet valid: current time 2023-09-12T11:15:59Z is after 2023-09-09T23:14:32Z 
```

The changes I did were only in hasura and related to permissions and relationships. 
I have tried to restart the containers, deleting the volumes, deleting the images, and composing up again and the error is still the same.
Thanks for your help,

**Comment by dbarrosop** [comment]
Please, update the cli to the latest version.
