### ISSUE TITLE
[Proposal] Change the usage of `HASURA_GRAPHQL_JWT_SECRET` to allow for JWT configuration beyond just the JWT key

### ISSUE THREAD

**Issue by atbe** [nhost/cli#771]
Hi all,

I'd like to be able to set more than just the `key` field on the `HASURA_GRAPHQL_JWT_SECRET` environment variable, to allow [for alternative options](https://hasura.io/docs/latest/auth/authentication/jwt/#hasura-jwt-configuration-options) to be set.

Currently, the `HASURA_GRAPHQL_JWT_SECRET` environment variable/nhost secret is used as the value for the `key` field of the configuration object, [as shown here](https://github.com/nhost/cli/blob/d12173a7ee2648477672261695347798fc901e32/project/config.go#L23).

My proposal is to either:
1. Change the `HASURA_GRAPHQL_JWT_SECRET` variable to actually set the entire environment variable value, so that the user can provide an entire JSON object that allows them to configure alternative hasura JWT options, like so:
    ```json
    {"key":"0f987876650b4a085e64594fae9219e7781b17506bec02489ad061fba8cb22db","type":"HS256"}
    ```
2. Allow for an additional environment variable, such as  `HASURA_GRAPHQL_JWT_OPTIONS` where if specified, the entire value is used as the `HASURA_GRAPHQL_JWT_SECRET` environment variable value.

Option 2 will save the team the hassle of having to update documentation and other items that assume that `HASURA_GRAPHQL_JWT_SECRET` is a secret value rather than a JSON object.

---

Depending on which proposal the team likes more, I'd be happy to provide a PR for the change.

Thank you to the nhost team for maintaining a fantastic set of OSS tooling on top of Hasura and for staying true to the ethos of allowing the entire stack to be run locally/self-hosted. 🥂

**Comment by dbarrosop** [comment]
This is already supported. You are probably confounding secrets with environment variables and haven't checked the configuration file. I'd suggest you to start by checking `nhost/nhost.toml` and looking for the jwt secret there. I'd also recommend you to read https://nhost.io/blog/config

I am closing because there I don't think there is anything to do but feel free to comment or reopen otherwise.

**Comment by atbe** [comment]
Thanks for the info, @dbarrosop I appreciate it!
