### ISSUE TITLE
allow multiline secrets in .secrets

### ISSUE THREAD

**Issue by andr-ec** [nhost/cli#782]
Currently when using a multiline variables in .secrets it will show an error: 
```
failed to validate config: failed to parse secrets, make sure secret values are between quotes: failed to unmarshal object: toml: basic strings cannot have new lines
```
I think .secrets should support multiline variables like a normal .env file.

**Comment by dbarrosop** [comment]
That is supported already. The secrets file is a toml file under the hoods so toml rules apply. Try with:

```
str1 = """
Roses are red
Violets are blue"""
```

Closing but feel free to reopen if it doesn't work.

**Comment by andr-ec** [comment]
This doesn't work, I get this error:
`failed to validate config: failed to validate config: failed to unmarshal config: invalid character '\n' in string literal`

**Comment by andr-ec** [comment]
@dbarrosop I don't have permissions to reopen, could you reopen or should I create a separate issue?

**Comment by dbarrosop** [comment]
@andr-ec yes, you were right and it was broken, hoever, as spakanati mentioned it should work on 1.8.0. Otherwise, let me know.
