### ISSUE TITLE
API isn't reloading on code changes

### ISSUE THREAD

**Issue by TaylorFacen** [nhost/cli#82]
version: nhost/0.4.1 darwin-x64 node-v12.18.3

Whenever I make a code change to a file in my project's `/api` folder, I need to shut down and reload the local environment in order for changes to take effect.

**Comment by elitan** [comment]
Fixed in https://github.com/nhost/cli/pull/75/commits/51c874f1a5d576360c03f3a0c2670729bc0e0d49
