### ISSUE TITLE
nhost sw version shows complete changelog

### ISSUE THREAD

**Issue by mainstreetmark** [nhost/cli#823]
I was on CLI v1.12.0, and my script checks for a new CLI version.

```
A new version of Nhost CLI is available: v1.13.0
You can upgrade by running `nhost sw upgrade`
Changes since your current version:
....
```

Despite saying "Changes since your current version", it dumps the changelog going all the way back to `v1.0.0`, rather than (in my case) just for `v1.13.0`.

**Comment by dbarrosop** [comment]
Thanks for reporting, will be fixed on #831
