### ISSUE TITLE
local environment starting, but is not accessible via local URLs

### ISSUE THREAD

**Issue by felixhagspiel** [nhost/cli#836]
I am using Docker version 25.0.3, nhost version 1.14.0 and I am running on a mac air m2 on Sonoma 14.3.1, and I have created a new nhost project today.

When I am running `nhost up` everything seems to complete without issues:

```
Nhost development environment started.
URLs:
- Postgres:         postgres://postgres:postgres@localhost:5432/local
- Hasura:           https://local.hasura.nhost.run
- GraphQL:          https://local.graphql.nhost.run
- Auth:             https://local.auth.nhost.run
- Storage:          https://local.storage.nhost.run
- Functions:        https://local.functions.nhost.run
- Dashboard:        https://local.dashboard.nhost.run
- Mailhog:          https://local.mailhog.nhost.run

SDK Configuration:
 Subdomain:    local
 Region:       (empty)
Run `nhost up` to reload the development environment
Run `nhost down` to stop the development environment
Run `nhost logs` to watch the logs
```

However, when I try to access any of the links, I get a 404 / `ERR_NAME_NOT_RESOLVED `. Do I have to add any entries in my `hosts` file? I have not found anything in the docs. Am I missing something?

**Comment by felixhagspiel** [comment]
seems like this PR solves it: https://github.com/nhost/cli/pull/692
I had to add `127.0.0.1 local.auth.nhost.run local.db.nhost.run local.functions.nhost.run local.graphql.nhost.run local.hasura.nhost.run local.storage.nhost.run` in my `/etc/hosts` file, now it is working. This was not necessary in earlier versions, and maybe should be mentioned in the docs

**Comment by dbarrosop** [comment]
That is not necessary unless your DNS servers are blocking DNS resolutions that return 127.0.0.1. If this didn't happen on prior versions the issue is most likely you have changed your DNS servers recently. You may want to check and look for some that don't block arbitrary requests.
