### ISSUE TITLE
nhost sw version still shows complete changelog

### ISSUE THREAD

**Issue by mainstreetmark** [nhost/cli#859]
Similar to #823, whenever i type `nhost sw version`, it tells me the version, tells me that the same version is available for upgrade and then dumps the entire revision history back to `0.6.7`

```
Nhost CLI 1.16.0 for darwin-arm64
A new version of Nhost CLI is available: v1.16.0
You can upgrade by running `nhost sw upgrade`
Changes since your current version:
v1.16.0
## Changes
...
```
I would expect it to say `Nhost CLI 1.16.0 for darwin-arm64` and leave it at that.  But it seems like a bug to say I'm on `1.16.0` and then tell me a new version `1.16.0` is available.

Even after `nhost sw upgrade`, `nhost sw version` offers an upgrade and dumps the entire revision log.

**Comment by dbarrosop** [comment]
thanks for reporting, will be fixed on the next release.
