### ISSUE TITLE
`nhost/metadata/tables.yaml` doesn't update when deleted from origin

### ISSUE THREAD

**Issue by MarcelloTheArcane** [nhost/cli#98]
I ran into some errors (#97) and so I deleted all the tables that I'd made.

However, when running `nhost dev` again, the same error message shows up.

I've found `tables.yaml` in the `nhost/metadata` folder which still shows the old tables.

Is there a way to re-fetch the tables from the origin?

**Comment by mrinalwahal** [comment]
We have released Nhost v2 since this issue was opened. Please try the latest infra, and if you still face new issues, feel free to open an issue.
